"""John chapters 9–14 — 50 questions each."""
from __future__ import annotations

from john_quiz_spec_utils import zip_chapter

# fmt: off
_CH9: list[tuple[str, str, str, str, str, str]] = [
("Why did the disciples ask whether sin caused the man's blindness?", "To link suffering to someone's sin", "To offer medicine", "To find his parents", "To test Moses", "Rabbi, who sinned, this man or his parents, that he was born blind? (John 9:2)."),
("What did Jesus say about the man's blindness?", "That God's works might be displayed", "That punishment was final", "That sin did not matter", "That he would never see", "It was not that this man sinned… but that the works of God might be displayed (John 9:3)."),
("What did Jesus make with his saliva?", "Mud", "Bread", "Oil", "Wine", "He spat on the ground and made mud with the saliva (John 9:6)."),
("Where did Jesus tell him to wash?", "The pool of Siloam", "The Jordan", "Bethesda", "Gibeon", "Go, wash in the pool of Siloam (John 9:7)."),
("What does Siloam mean?", "Sent", "Peace", "Light", "Judge", "Which means Sent (John 9:7)."),
("On what day did the neighbors debate his healing?", "The Sabbath", "Passover", "Tabernacles", "The Day of Atonement", "Now it was a Sabbath day when Jesus made the mud and opened his eyes (John 9:14)."),
("Why did some Pharisees say Jesus was not from God?", "Because he did not keep the Sabbath", "Because he was from Galilee", "Because he was young", "Because he avoided the temple", "This man is not from God, for he does not keep the Sabbath (John 9:16)."),
("What division occurred among the Pharisees?", "Whether Jesus was a sinner", "Whether Moses existed", "Whether Rome should rule", "Whether fish were clean", "There was a division among them (John 9:16)."),
("What did the healed man call Jesus when questioned?", "A prophet", "A priest", "A king of Rome", "An angel", "He is a prophet (John 9:17)."),
("What did the Jews do to his parents?", "Asked how he received sight", "Stoned them", "Made them priests", "Sent them to Rome", "They asked them, \"Is this your son, who you say was born blind?\" (John 9:19)."),
("Why were parents afraid to speak freely?", "For fear of the Jews", "For fear of storms", "For fear of poverty", "For fear of boats", "His parents said these things because they feared the Jews (John 9:22)."),
("What had the Jews agreed about confessing Jesus?", "Put out of the synagogue", "Pay a fine", "Fast weekly", "Leave Judea", "For the Jews had already agreed… if anyone should confess Jesus to be Christ, he was to be put out of the synagogue (John 9:22)."),
("What did the man say about Jesus opening his eyes?", "Whether he is a sinner I do not know; one thing I know: I was blind, now I see", "I know nothing", "He is a fraud", "I refuse to say", "Whether he is a sinner I do not know. One thing I know, that though I was blind, now I see (John 9:25)."),
("What did Jesus ask him when he found him after being cast out?", "Do you believe in the Son of Man?", "Will you be a priest?", "Will you pay tithe?", "Will you leave Galilee?", "Jesus… found him and said, \"Do you believe in the Son of Man?\" (John 9:35)."),
("Whom did the man worship?", "Jesus", "The temple", "Moses", "Angels only", "He said, \"Lord, I believe,\" and he worshiped him (John 9:38)."),
("For judgment Jesus came into the world, that who might see?", "The blind", "The rich", "The priests", "The Romans", "For judgment I came into this world, that those who do not see may see (John 9:39)."),
("What did Jesus say some who see would become?", "Blind", "Rich", "Kings", "Angels", "That those who see may become blind (John 9:39)."),
("What did some Pharisees ask?", "Are we also blind?", "Are we also deaf?", "Are we also poor?", "Are we also Romans?", "Some of the Pharisees… said, \"Are we also blind?\" (John 9:40)."),
("What did Jesus say guilt remained on if they claimed to see?", "Their sin", "Their poverty", "Their families", "Their houses", "If you were blind, you would have no guilt; but now that you say, 'We see,' your guilt remains (John 9:41)."),
("What did the neighbors debate — is this the man who used to sit and beg?", "Whether he was the same man", "Whether he was a priest", "Whether he was Roman", "Whether he was rich", "Is this not the man who used to sit and beg? (John 9:8)."),
("Theologically, how does physical sight/healing function as a sign in John 9?", "It reveals Jesus as light of the world and exposes spiritual blindness", "It is only medical", "It denies faith", "It ends the Gospel", "I am the light of the world (John 9:5)."),
("How does the parents' fear of the synagogue relate to community pressure?", "Faith in Jesus carried social cost — exclusion", "Synagogue was unimportant", "Everyone was bold", "Only Romans feared", "His parents… feared the Jews (John 9:22)."),
("What does the beggar's boldness before leaders contrast with?", "Parents' timidity — courage of new sight", "Jesus' silence", "Roman courage", "Women's silence", "The man defends Jesus before authorities (John 9:24–34)."),
("How does John 9 connect to John 8's light theme?", "Continues seeing/blindness as moral and spiritual reality", "Contradicts chapter 8", "Ignores light", "Only physical", "I am the light of the world (John 9:5)."),
("What irony appears in Pharisees claiming Moses discipleship?", "They reject one greater than Moses while appealing to Moses", "They love Jesus", "They ignore Moses", "They follow Jesus", "We know that God has spoken to Moses (John 9:28–29)."),
("Scholarly note: what is debated about sin and blindness in 9:3?", "Not all suffering is punitive — display of God's works", "All suffering is always punishment", "Sin never matters", "John denies providence", "Neither this man sinned nor his parents (John 9:3)."),
("How does worship in 9:38 advance John's Christology?", "Jesus receives worship fitting for God", "Worship is refused", "Only Father is worshiped in John", "Worship is idolatry", "He worshiped him (John 9:38)."),
("What does being cast out foreshadow for the community of believers?", "Cost of confessing Christ — later expulsions in John's context", "Nothing", "Joy only", "Wealth", "They cast him out (John 9:34)."),
("How does the man born blind function as a foil to the seeing Pharisees?", "He gains sight and insight while they remain blind", "Both are blind", "Both see", "Pharisees are humble", "Are we also blind? (John 9:40–41)."),
("What does \"wash\" evoke beyond physical act?", "Cleansing and obedience to Jesus' word — baptism echoes", "Only hygiene", "Only pool rules", "Roman baths", "He went and washed and came back seeing (John 9:7)."),
("How does John 9 prepare for the good shepherd discourse?", "Sheep/shepherd imagery follows in ch. 10", "No connection", "Shepherd is absent", "Only wolves matter", "Leads into John 10."),
("What does Jesus say about doing God's works while day lasts?", "We must work the works of him who sent me", "We must rest always", "We must avoid work", "We must wait for night", "We must work the works of him who sent me while it is day (John 9:4)."),
("What night language appears in John 9:4?", "Night is coming when no one can work", "Night is best for work", "Night is irrelevant", "Night is only for sleep", "Night is coming, when no one can work (John 9:4)."),
("How does the healed man's progression in titles mirror understanding?", "From prophet to worshiping Lord — deepening faith", "Titles never change", "He denies Jesus", "He only says \"man\"", "He is a prophet… Lord, I believe (John 9:17–38)."),
("What rhetorical effect does repeated interrogation have?", "Shows leaders' hardness and the man's growing courage", "Shows fairness only", "Shows boredom", "Shows Roman law", "They reviled him (John 9:28)."),
("How does guilt remain on those who claim to see?", "Self-righteousness blocks grace — culpable blindness", "No guilt possible", "Guilt is only for Gentiles", "Seeing removes guilt", "Your guilt remains (John 9:41)."),
("What connection exists between mud and creation imagery?", "God formed man from ground — Jesus as new creation act", "Mud is random", "Genesis is rejected", "Only spit matters", "He spat on the ground and made mud (John 9:6)."),
("How does Siloam's name (Sent) fit mission theology?", "Jesus is the sent one; washing in sent water fits", "Name is random", "Sent means only postal", "Siloam is pagan", "Which means Sent (John 9:7)."),
("What does the chapter teach about partial knowledge?", "From \"I don't know\" to worship — progressive revelation", "Knowledge is impossible", "First impression is final", "Leaders know best", "Whether he is a sinner I do not know… (John 9:25)."),
("How does John 9's sign relate to signs in John overall?", "Seventh sign sequence builds toward Lazarus — life from darkness", "Signs stop at 9", "Signs are anti-faith", "John hates signs", "Sign reveals God's works (John 9:3–4)."),
("What pastoral lesson comes from the man's simple testimony?", "Experience of grace can be defended simply — \"I was blind, now I see\"", "Complex theology only", "Silence is best", "Testimony is sin", "One thing I know (John 9:25)."),
("How does Jesus find the man after exclusion?", "Pastoral care for the outcast — Jesus seeks the rejected", "Jesus ignores him", "Man finds Jesus alone", "Angels mediate", "Jesus heard that they had cast him out, and found him (John 9:35)."),
("What eschatological hint is in seeing judgment?", "Ultimate separation of sight and blindness — final accountability", "No judgment in John", "Judgment is only Roman", "Everyone sees equally", "For judgment I came (John 9:39)."),
("How does the chapter answer the disciples' opening question?", "Not sin's cause but God's glory in mercy — reframes suffering", "Sin is always the parent's fault", "Suffering is meaningless", "Blindness is only metaphor", "That the works of God might be displayed (John 9:3)."),
("What does being \"put out\" linguistically connect to later?", "Apostasy trials — same vocabulary as community exclusion", "No later use", "Only physical exile", "Only wealth loss", "Put out of the synagogue (John 9:22, 34)."),
("How does the blind man's wit in dialogue serve John's polemic?", "Exposes leaders' inconsistency without seminary training", "Shows education saves", "Shows Pharisees are right", "Shows Romans win", "You would not listen… why do you want to hear it again? (John 9:27)."),
("What christological step is \"Son of Man\" in 9:35?", "Moves from healer to Messianic identity — Danielic title", "Denies messiahship", "Only human title", "Roman title", "Do you believe in the Son of Man? (John 9:35)."),
("How does John 9 balance divine sovereignty and human response?", "God's works displayed and man must wash/believe", "Only fate", "Only works", "No human role", "Go, wash… Do you believe? (John 9:7, 35)."),
("What did the Pharisees say about the man born blind?", "You were steeped in sin at birth; how dare you lecture us!", "You are our teacher", "You should be a priest", "You are innocent", "You were steeped in sin at birth; how dare you lecture us! (John 9:34)."),
("What did the healed man ask the Pharisees about wanting to become disciples?", "Do you want to become his disciples too?", "Will you pay me?", "Where is Siloam?", "Who is Moses?", "You want to become his disciples, too? (John 9:27)."),
]

_CH10: list[tuple[str, str, str, str, str, str]] = [
("What figure opens John 10?", "Sheepfold / sheep", "Vineyard", "Temple treasury", "Fishing boat", "Truly… he who does not enter… by the door… (John 10:1)."),
("Who is the shepherd of the sheep?", "The one who enters by the door", "The wolf", "The buyer", "The Roman soldier", "The sheep hear his voice, and he calls his own sheep by name (John 10:3)."),
("What does the shepherd call his own sheep?", "By name", "By number only", "By color only", "By lot", "He calls his own sheep by name (John 10:3)."),
("What does Jesus say he is in John 10:7?", "The door of the sheep", "The wall", "The coin", "The whip", "I am the door of the sheep (John 10:7)."),
("What does Jesus say thieves and robbers come to do?", "Steal and kill and destroy", "Build the fold", "Heal sheep", "Teach the law", "The thief comes only to steal and kill and destroy (John 10:10)."),
("What does the good shepherd come to give?", "Abundant life", "Wealth", "Roman citizenship", "A crown only", "I came that they may have life and have it abundantly (John 10:10)."),
("What does the good shepherd do for the sheep?", "Lay down his life", "Flee always", "Sell them", "Hide from wolves", "The good shepherd lays down his life for the sheep (John 10:11)."),
("What does the hired hand do when he sees the wolf?", "Flees", "Fights", "Prays", "Calls Rome", "He flees… and the wolf snatches them (John 10:12)."),
("What does Jesus say he has that are not of this fold?", "Other sheep", "Other wolves", "Other thieves", "Other doors", "I have other sheep that are not of this fold (John 10:16)."),
("What will the sheep do?", "Become one flock with one shepherd", "Fight each other", "Join wolves", "Abandon the shepherd", "There will be one flock, one shepherd (John 10:16)."),
("When was the feast of dedication in John?", "Winter", "Spring", "Summer", "Autumn", "At that time the Feast of Dedication took place at Jerusalem. It was winter (John 10:22)."),
("Where was Jesus walking in Solomon's Colonnade?", "In the temple", "In the Jordan", "On the sea", "In Nazareth", "Jesus was walking in the temple, in the colonnade of Solomon (John 10:23)."),
("What did the Jews ask Jesus?", "How long will you keep us in suspense? If you are the Christ, tell us plainly", "When will Rome fall?", "When is Passover?", "Who is your mother?", "How long will you keep us in suspense? If you are the Christ, tell us plainly (John 10:24)."),
("What works did Jesus say his sheep do regarding his voice?", "Follow him", "Ignore him", "Betray him", "Judge him", "My sheep hear my voice, and I know them, and they follow me (John 10:27)."),
("What does Jesus give his sheep?", "Eternal life", "Money", "Land in Rome", "A sword only", "I give them eternal life, and they will never perish (John 10:28)."),
("Who can snatch Jesus' sheep from his hand?", "No one", "Angels", "Sin", "Wolves always", "No one will snatch them out of my hand (John 10:28)."),
("Whose hand is greater — Father or Son?", "Greater than all; Father and Son are one in keeping", "Father is weaker", "Son has no sheep", "Hands are metaphor only", "No one is able to snatch them out of the Father's hand (John 10:29)."),
("What did Jesus say he and the Father are?", "One", "Two unrelated gods", "Enemies", "Partners in business only", "I and the Father are one (John 10:30)."),
("What did the Jews pick up again?", "Stones", "Sticks", "Money", "Scrolls", "The Jews picked up stones again to stone him (John 10:31)."),
("What did Jesus appeal to from his Father?", "Good works shown them", "Roman law", "Moses' rod", "Temple gold", "If I am not doing the works of my Father, do not believe me (John 10:37)."),
("Where did many believe beyond the Jordan?", "Where John had been baptizing at first", "In Rome", "In Egypt", "In Tyre", "Many came to him… where John had been baptizing at first (John 10:40)."),
("What did John testify about Jesus at that place?", "That everything John said about this man was true", "That Jesus was a fraud", "That baptism ended", "That Rome was chosen", "John did no sign, but everything that John said about this man was true (John 10:41)."),
("Theologically, what does shepherd imagery draw from?", "Ezekiel 34 and Psalm 23 — God as shepherd replacing bad shepherds", "Only Greek myths", "Only Roman farming", "No Old Testament", "I am the good shepherd (John 10:11)."),
("How does laying down life connect to crucifixion prolepsis?", "Foreshadows voluntary substitutionary death", "Foreshadows running away", "Denies cross", "Only metaphor with no death", "I lay down my life… I lay it down of my own accord (John 10:17–18)."),
("What does the door image emphasize?", "Exclusive access to salvation through Christ", "Many doors", "Doors are irrelevant", "Law is the door", "I am the door. If anyone enters by me, he will be saved (John 10:9)."),
("How does hireling contrast protect the church?", "Leaders who abandon in danger vs. Christ's constancy", "Hirelings are best", "Shepherds are unnecessary", "Wolves are good", "He flees… because he is a hired hand (John 10:12–13)."),
("What does unity of flock suggest about Gentile mission?", "One shepherd gathers sheep beyond Israel", "Only Jews saved", "Flocks must fight", "Sheep stay in one country", "Other sheep… there will be one flock (John 10:16)."),
("How does John 10:30 trigger charges?", "Oneness with Father sounds like blasphemy to opponents", "Sounds like peace", "Ignored by all", "Only disciples hear", "We are stoning you… because you… make yourself God (John 10:33)."),
("What defense does Jesus use from Psalm 82?", "Gods language for judges — his claim is lesser yet true", "Psalms are invalid", "He denies Scripture", "He quotes Homer", "If he called them gods… can you say… you are blaspheming? (John 10:34–36)."),
("What does Jesus say the Father set him apart and sent him into the world as?", "Holy", "Rich", "Silent", "Angry", "Whom the Father consecrated and sent into the world (John 10:36)."),
("How does eternal security language read in Reformed vs Arminian debate?", "Debated whether \"snatch\" teaches perseverance vs. warning elsewhere", "All agree instantly", "John teaches easy-believism without fruit", "No debate exists", "No one will snatch them out of my hand (John 10:28)."),
("What feast setting links chapters 9–10?", "Hanukkah — light and dedication themes", "Passover only", "No feast", "Pentecost", "Feast of Dedication… winter (John 10:22)."),
("How does Jesus escape in 10:39?", "Across the Jordan — withdrawal until hour", "To Rome", "By fighting", "He does not escape", "He went away again across the Jordan (John 10:40)."),
("What does knowing sheep by name imply?", "Personal relationship — not anonymous mass", "Names are secret", "Sheep are numbered only", "Only OT priests know names", "He calls his own sheep by name (John 10:3)."),
("How does the chapter answer \"Are you the Christ?\"", "Works and sheep testify — plain yet rejected", "Jesus says no", "Jesus is silent", "Jesus denies Messiahship", "The works… in my Father's name bear witness about me (John 10:25)."),
("What wolf imagery contributes?", "External persecution and internal abandonment contrasted with good shepherd", "Wolves are pets", "No danger exists", "Only internal sin", "The wolf snatches them and scatters them (John 10:12)."),
("How does voluntary laying down life fit John's agency language?", "Jesus actively chooses death per Father's command — not mere passivity", "Jesus is passive only", "Romans force without purpose", "No command", "I have authority to lay it down, and I have authority to take it up again (John 10:18)."),
("What pastoral application comes from voice recognition?", "Sheep discern Christ's word amid many voices", "All voices equal", "Hearing is impossible", "Only scholars hear", "The sheep follow him, for they know his voice (John 10:4)."),
("How does 10:16 relate to John's global vision?", "Unity of Jew and Gentile in Christ — one flock", "Nationalism forever", "Two flocks fight", "Gentiles excluded", "Other sheep… one flock (John 10:16)."),
("What christological title cluster appears in chapter 10?", "Good shepherd, door, one with Father", "King only", "Prophet only", "Angel only", "I am the good shepherd (John 10:11, 14)."),
("How does belief across the Jordan contrast Jerusalem hostility?", "Receiving region responds where prophet ministry began", "Everyone hates", "Jordan is cursed", "Baptism site is irrelevant", "Many believed in him there (John 10:42)."),
("What link exists between baptism witness and Jesus?", "John's witness points to Jesus — continuity", "John competes", "John is greater", "Baptism replaces Jesus", "John… bore witness to the truth (John 5:33)."),
("How does stone-throwing motif connect John 8–10?", "Repeated rejection after divine claims", "Stones are friendly", "Only once", "Only disciples throw", "The Jews picked up stones again (John 10:31)."),
("What does \"stranger's voice\" sheep flee from?", "False teachers — discernment", "They never flee", "They love strangers", "Only food matters", "A stranger they will not follow, but they will flee from him (John 10:5)."),
("How does abundant life differ from mere existence?", "Quality of eternal communion — not only longevity", "Only wealth", "Only health", "Only fame", "Life… abundantly (John 10:10)."),
("What Trinitarian hint is in sheep in Father's and Son's hands?", "Mutual divine grip — security in Father-Son unity", "Father and Son compete", "Only one person", "Hands are fiction", "No one snatches from my hand… Father's hand (John 10:28–29)."),
("What did Jesus say thieves do instead of entering by the door?", "Climb in by another way", "Knock politely", "Repair the wall", "Pay the shepherd", "He who does not enter the sheepfold by the door but climbs in by another way (John 10:1)."),
("Who is the shepherd of the sheep according to the doorkeeper?", "The one who enters by the door", "The wolf", "The buyer", "The Roman guard", "The sheep hear his voice… he calls his own sheep (John 10:2–3)."),
("What does Jesus say happens to the sheep who follow him?", "They will never perish", "They will lose their way", "They will become wolves", "They will deny him", "I give them eternal life, and they will never perish (John 10:28)."),
("What feast is named in John 10:22?", "Feast of Dedication", "Passover", "Pentecost", "Tabernacles", "The Feast of Dedication took place at Jerusalem. It was winter (John 10:22)."),
]

_CH11: list[tuple[str, str, str, str, str, str]] = [
("Who was sick in Bethany?", "Lazarus", "Nicodemus", "Zacchaeus", "Barabbas", "Now a certain man was ill, Lazarus of Bethany (John 11:1)."),
("Whose brother was Lazarus?", "Mary and Martha", "Peter and Andrew", "James and John", "Joseph and Simon", "Mary was the one who anointed the Lord… her brother Lazarus was ill (John 11:1–2)."),
("What did Jesus say about Lazarus' illness?", "It is for God's glory", "It is hopeless", "It is punishment only", "It is fake", "This illness does not lead to death. It is for the glory of God (John 11:4)."),
("How long did Jesus stay where he was when he heard Lazarus was sick?", "Two days", "One hour", "Seven days", "Forty days", "So he stayed two days longer in the place where he was (John 11:6)."),
("What did Jesus say about walking in the day?", "He does not stumble because he sees the light of this world", "He always stumbles", "He needs a lamp", "He avoids work", "If anyone walks in the day, he does not stumble (John 11:9)."),
("What did Martha say when she met Jesus?", "Lord, if you had been here, my brother would not have died", "Lord, go away", "Lord, we need money", "Lord, teach us to fish", "Lord, if you had been here, my brother would not have died (John 11:21)."),
("What did Jesus tell Martha her brother would do?", "Rise again", "Remain dead forever", "Live in memory only", "Return as an angel", "Your brother will rise again (John 11:23)."),
("What did Martha confess Jesus to be?", "The Christ, the Son of God", "A prophet only", "A priest only", "A teacher only", "I believe that you are the Christ, the Son of God (John 11:27)."),
("What did Mary do when she came to Jesus?", "Fell at his feet", "Ran away", "Argued with Martha", "Called the Romans", "She fell at his feet, saying to him, \"Lord, if you had been here…\" (John 11:32)."),
("How did Jesus respond when he saw Mary weeping?", "He was deeply moved in spirit and troubled", "He laughed", "He left immediately", "He rebuked her", "He was deeply moved in his spirit and greatly troubled (John 11:33)."),
("What did Jesus do at the tomb?", "Wept", "Shouted angrily", "Refused to look", "Built a monument", "Jesus wept (John 11:35)."),
("What did Jesus say to remove from the stone?", "The stone", "The body", "The mourners", "The disciples", "Take away the stone (John 11:39)."),
("What did Martha warn about?", "That there would be an odor — four days dead", "That Romans would come", "That Lazarus was alive", "That the tomb was empty", "Lord, by this time there will be an odor for he has been dead four days (John 11:39)."),
("What did Jesus cry with a loud voice?", "Lazarus, come out", "Father, forgive", "Peace, be still", "Eli, Eli", "He cried out with a loud voice, \"Lazarus, come out\" (John 11:43)."),
("Who did Lazarus come out bound with?", "Hand and foot with linen strips", "Chains", "Gold", "Roman ropes", "The man who had died came out, his hands and feet bound with linen strips (John 11:44)."),
("What did the chief priests plan to do to Lazarus?", "Put him to death", "Make him king", "Send him to Rome", "Honor him", "The chief priests plotted to put Lazarus to death as well (John 12:10–11)."),
("What did Caiaphas say was expedient?", "That one man should die for the people", "That Rome should rule", "That the temple should close", "That disciples should fight", "It is better for you that one man should die for the people (John 11:50)."),
("What did Caiaphas prophesy unknowingly?", "That Jesus would die for the nation — and gather children of God scattered abroad", "That Rome would convert", "That the temple would never fall", "That all would reject Jesus", "Jesus would die for the nation, and not for the nation only, but also to gather into one the children of God (John 11:51–52)."),
("From that day on what did they plan to do?", "Put Jesus to death", "Crown him", "Make him high priest", "Send him to Greece", "So from that day on they made plans to put him to death (John 11:53)."),
("Why did Jesus no longer walk openly among the Jews?", "Because they sought to kill him", "Because he was tired", "Because he hated Jerusalem", "Because he feared Lazarus", "Jesus therefore no longer walked openly among the Jews (John 11:54)."),
("Theologically, why delay two days?", "God's glory displayed in resurrection, not mere healing", "Jesus was lazy", "Travel was impossible", "Disciples refused", "Loved… yet… he stayed two days (John 11:5–6)."),
("How is Jesus' weeping compatible with knowing he would raise Lazarus?", "Compassion with human grief — empathy is real", "He pretended", "He doubted", "He wept for himself", "Jesus wept (John 11:35)."),
("What does resurrection now vs last day mean in Martha's dialogue?", "Jesus is the resurrection — present power and future hope", "Only future matters", "Only past matters", "Resurrection is myth", "I am the resurrection and the life (John 11:25)."),
("How does Lazarus sign relate to Jesus' own resurrection?", "Preview of Christ's victory over death — plot to kill both", "Contradicts Easter", "Lazarus is irrelevant", "Signs end here", "They planned to put Lazarus to death (John 12:10)."),
("What does the plot against Lazarus show about hardness?", "Rejecting sign leads to murder — moral blindness", "Leaders convert", "Miracles always convince", "Lazarus is safe", "Plot to kill Lazarus (John 12:10)."),
("How does Caiaphas's prophecy read ironically?", "Enemy speaks truth — substitutionary atonement for nation", "Caiaphas is righteous", "Prophecy is impossible", "High priests never speak", "He prophesied that Jesus would die for the nation (John 11:51)."),
("What does \"gather children of God scattered\" hint?", "Gentile inclusion — one new people", "Only Judea", "Scattering is good", "No mission", "Gather into one the children of God who are scattered abroad (John 11:52)."),
("How does Thomas' \"Let us go, that we may die with him\" function?", "Courage and misunderstanding — loyalty amid danger", "Thomas refuses", "Thomas betrays", "Thomas is absent", "Let us also go, that we may die with him (John 11:16)."),
("What does stinking corpse detail contribute?", "Real death — miracle is not resuscitation theater", "Lazarus was not dead", "Odor is metaphor", "Four days is symbolic only", "There will be an odor (John 11:39)."),
("How does unbinding Lazarus picture discipleship?", "Loose him, let him go — community role after Jesus calls", "Binding is permanent", "Community irrelevant", "Lazarus stays bound", "Unbind him, and let him go (John 11:44)."),
("What christological climax is \"I am the resurrection and the life\"?", "Jesus is source of resurrection life — present eschatology", "Resurrection is only doctrine", "Jesus is only teacher", "Life is abstract", "I am the resurrection and the life (John 11:25)."),
("How does belief \"though he die, yet shall he live\" work?", "Participation in Christ's resurrection life", "Reincarnation", "Only metaphor", "No future life", "Whoever believes in me, though he die, yet shall he live (John 11:25)."),
("What pastoral word is in Jesus' grief at tomb?", "Jesus enters our sorrow — not stoic distance", "Jesus ignores mourners", "Grief is sin", "Tears are weakness only", "Jesus wept (John 11:35)."),
("How does crowd's reaction split?", "Many believe; some report Pharisees — mixed response", "All believe", "None notice", "Only women believe", "Many… believed in him (John 11:45)."),
("What Sanhedrin fear drives plot?", "If they let him go on, Romans will come — political fear", "Spiritual zeal only", "Love of God only", "Indifference", "If we let him go on like this, everyone will believe in him, and the Romans will come (John 11:48)."),
("How does Bethany location matter?", "Near Jerusalem — public sign before Passover crowd", "Far from witnesses", "Unknown town", "Only symbolic", "Bethany was near Jerusalem (John 11:18)."),
("What does Mary's anointing forward reference add?", "Connects to burial anointing in chapter 12", "Disconnects chapters", "Only decoration", "Only Judas", "This Mary… anointed the Lord with ointment (John 11:2)."),
("Scholarly debate: historicity of Lazarus?", "Arguments for core event vs. symbolic reading — majority take narrative seriously", "All scholars deny", "John is pure fiction", "No debate", "Scholarship varies on details, not always on genre."),
("How does 11:48 show misunderstanding of messianic hope?", "Messiah as national liberator feared by Rome — wrong lens", "Messiah is only priest", "Rome is friend", "No fear exists", "The Romans will come and take away both our place and our nation (John 11:48)."),
("What does Jesus' thanks to Father before tomb show?", "Prayerful dependence — public thanks for heard prayer", "Pride", "Doubt", "Silence to Father", "Father, I thank you that you have heard me (John 11:41)."),
("How does crowd witness to raising affect plot?", "Sign becomes last straw for authorities — accelerates passion", "Authorities rejoice", "Sign is private", "No one hears", "Many… saw what he did, believed in him (John 11:45)."),
("What does \"Come out\" evoke?", "Creation word — new creation life", "Military command only", "Random shout", "Magic spell", "Lazarus, come out (John 11:43)."),
("How does Martha's service contrast Mary's sitting in Luke vs John focus?", "John highlights confession and dialogue — different emphasis", "Contradicts Luke", "Martha is absent", "Mary never speaks", "Martha served… Mary sat (cf. Luke 10) — John highlights faith confession (John 11:27)."),
("What hope is for \"everyone who lives and believes in me shall never die\"?", "Spiritual death defeated — eternal life quality", "No physical death ever", "Immortality of soul only Greek", "Death wins", "Everyone who lives and believes in me shall never die (John 11:26)."),
("How does Jesus being deeply moved challenge Greek impassibility debates?", "Divine compassion — emotion in incarnation", "God cannot feel", "Anger only", "Troubled means sin", "Deeply moved in his spirit (John 11:33)."),
("What narrative function does Lazarus have before Passion week?", "Final sign provoking decision — life confrontation", "Filler only", "Breaks tension", "Unrelated to cross", "They plotted to put him to death (John 11:53)."),
("How many days had Lazarus been in the tomb when Jesus arrived?", "Four days", "One day", "Seven days", "Forty days", "Lazarus has been in the tomb four days (John 11:17)."),
("What did Jesus say to the Father before calling Lazarus out?", "That he always heard him, for the sake of the crowd standing by", "That he doubted", "That Lazarus was unworthy", "That Martha was wrong", "I knew that you always hear me, but I said this on account of the people standing around (John 11:42)."),
("What did many Jews who came to Mary conclude about Jesus?", "That if he had been there, Lazarus would not have died", "That Jesus was a fraud", "That Lazarus was alive already", "That Rome should judge", "Could not he who opened the eyes of the blind man also have kept this man from dying? (John 11:37)."),
("What did Jesus say to take away from Lazarus' face?", "The cloth", "The stone only", "His money", "His sisters", "The dead man came out, his hands and feet bound… Jesus said to them, \"Unbind him, and let him go\" (John 11:44)."),
]

_CH12: list[tuple[str, str, str, str, str, str]] = [
("Whose house did Jesus visit six days before Passover?", "Lazarus", "Zacchaeus", "Simon the Pharisee", "Nicodemus", "Six days before the Passover, Jesus therefore came to Bethany, where Lazarus was (John 12:1)."),
("Who anointed Jesus' feet?", "Mary", "Martha", "Lazarus", "Judas", "Mary therefore took a pound of expensive ointment… and anointed the feet of Jesus (John 12:3)."),
("Who complained about the ointment?", "Judas Iscariot", "Peter", "Thomas", "Pharisees", "But Judas Iscariot… said, \"Why was this ointment not sold…?\" (John 12:4–5)."),
("What did Jesus say Mary bought the ointment for?", "The day of my burial", "A wedding feast", "A Roman tax", "Her own vanity", "Leave her alone, so that she may keep it for the day of my burial (John 12:7)."),
("What did the great crowd come to see?", "Lazarus", "The temple", "Pilate", "Herod", "The crowd came… because they heard that Jesus had raised Lazarus (John 12:9)."),
("What did the crowd cry on Palm Sunday?", "Hosanna! Blessed is he who comes in the name of the Lord", "Crucify him", "Away with Rome", "Blessed be Caesar", "Hosanna! Blessed is he who comes in the name of the Lord, even the King of Israel! (John 12:13)."),
("What did Jesus find?", "A young donkey", "A war horse", "A camel", "A chariot", "Jesus found a young donkey and sat on it (John 12:14)."),
("What did Jesus' disciples not understand at first?", "That these things were written about him", "That Lazarus was dead", "That Passover was near", "That Judas would betray", "His disciples did not understand these things at first (John 12:16)."),
("Who asked to see Jesus?", "Some Greeks", "Roman senators", "Egyptian priests", "Pharisees only", "Now among those who went up to worship at the feast were some Greeks (John 12:20)."),
("What did Jesus say a grain of wheat must do?", "Die to bear much fruit", "Grow taller", "Stay in the barn", "Feed birds only", "Unless a grain of wheat falls into the earth and dies, it remains alone (John 12:24)."),
("What did Jesus say his soul was?", "Troubled", "Peaceful only", "Ignorant", "Sinful", "Now is my soul troubled. And what shall I say? (John 12:27)."),
("What did a voice from heaven say?", "I have glorified it, and I will glorify it again", "You are wrong", "Stay in Galilee", "Fear the Romans", "I have glorified it, and I will glorify it again (John 12:28)."),
("What did the crowd say the voice was?", "Thunder or an angel", "A demon", "A trumpet from Rome", "Silence", "The crowd… said that it had thundered. Others said, \"An angel has spoken to him\" (John 12:29)."),
("What did Jesus say now is the judgment of this world?", "Now the ruler of this world will be cast out", "Now Rome falls", "Now the temple ends", "Now peace comes", "Now is the judgment of this world; now will the ruler of this world be cast out (John 12:31)."),
("What did Jesus say he would draw when lifted up?", "All people to himself", "Only Jews", "Only angels", "Only soldiers", "I, when I am lifted up from the earth, will draw all people to myself (John 12:32)."),
("What did Jesus say people loved instead of light?", "Darkness", "Truth", "Parents", "Scripture", "People loved the darkness rather than the light (John 12:43)."),
("What did Isaiah say about belief?", "Who has believed what he heard from us?", "Everyone believes", "No one heard", "Belief is automatic", "Isaiah said these things because he saw his glory and spoke of him (John 12:41)."),
("What could Jesus not do because the hour had not yet come?", "Nothing — the Father gave him authority over timing in Johannine sense", "Heal", "Teach", "Love", "Jesus answered them, \"The hour has come for the Son of Man to be glorified\" (John 12:23)."),
("How many days before Passover was the supper?", "Six", "Three", "One", "Forty", "Six days before the Passover, Jesus came to Bethany (John 12:1)."),
("What did Mary wipe Jesus' feet with?", "Her hair", "A towel only", "Sand", "Leaves", "She wiped his feet with her hair (John 12:3)."),
("Theologically, what does anointing for burial anticipate?", "Passion and royal anointing — messianic king going to death", "Only hygiene", "Only party", "Only Judas' anger", "Kept for the day of my burial (John 12:7)."),
("How do Greeks seeking Jesus symbolize mission?", "Gentiles drawn — \"hour\" for all nations", "Greeks reject", "Only Jews matter", "Greeks are villains", "We wish to see Jesus (John 12:21)."),
("What does grain of wheat dying teach about discipleship?", "Life through death — pattern of Jesus and followers", "Avoid suffering", "Death ends fruit", "Only farmers matter", "Unless it dies, it remains alone (John 12:24)."),
("How does voice from heaven function?", "Father's approval of cross — glorification theme", "Random weather", "Jesus' imagination", "Crowd hallucination", "I have glorified it, and I will glorify it again (John 12:28)."),
("What ruler is cast out?", "Satan — defeat through cross", "Pilate", "Herod", "Moses", "The ruler of this world will be cast out (John 12:31)."),
("How does unbelief fulfill Isaiah 53 / 6?", "Hardening — God's word still judges", "Isaiah is wrong", "Everyone believes", "Prophecy fails", "Isaiah said these things because he saw his glory (John 12:41)."),
("What fear did rulers have?", "Being put out of the synagogue", "Storms", "Fish shortage", "Roman taxes only", "They loved the glory that comes from man more than the glory that comes from God (John 12:43)."),
("How does triumphal entry quote Zechariah?", "King humble on donkey — messianic claim", "Military king on horse", "No prophecy", "Only human king", "Fear not, daughter of Zion; behold, your king is coming, sitting on a donkey's colt (John 12:15)."),
("What does Jesus' troubled soul humanize?", "Real struggle before cross — not cold stoicism", "Sin in Jesus", "Doubt of Father", "Fear of crowds", "Now is my soul troubled (John 12:27)."),
("What does \"lifted up\" mean?", "Crucifixion exaltation — drawing all peoples", "Only ascension", "Only resurrection", "Only teaching", "When I am lifted up from the earth (John 12:32)."),
("How does crowd misunderstanding of voice mirror spiritual dullness?", "Thunder vs angel — missing divine speech", "Everyone understood", "Voice is clear", "Only disciples confused", "It had thundered… an angel (John 12:29)."),
("What does Mary's costly worship model?", "Extravagant love — Judas' cheapness contrasts", "Waste of money always", "Hypocrisy", "Public show only", "Anointed… house was filled with the fragrance (John 12:3)."),
("How does Lazarus' presence provoke chief priests?", "Sign credibility threatens leadership — plot thickens", "They love Lazarus", "Lazarus is hidden", "No reaction", "The chief priests made plans to put Lazarus to death (John 12:10)."),
("What does \"the hour\" theme climax toward?", "Glorification through death — John's turning point", "Only miracles", "Only teaching", "End of Gospel", "The hour has come for the Son of Man to be glorified (John 12:23)."),
("How does belief of crowd contrast authorities?", "Populace welcomes; leaders reject — passion setup", "Authorities believe all", "Crowd is absent", "Everyone agrees", "The Pharisees said… Look, the world has gone after him (John 12:19)."),
("What does fragrance filling house suggest?", "Worship impact — gospel spreads scent", "Only smell", "House decay", "Judas likes it", "The house was filled with the fragrance of the perfume (John 12:3)."),
("Scholarly view: historicity of entry?", "Core event widely accepted; details harmonized across Gospels", "All deny entry", "Only John happened", "No scholarship", "Majority accept some historical kernel."),
("How does Jesus' answer about hating life in 12:25 relate to discipleship?", "Self-denial follows cruciform pattern", "Hate is literal for all", "Life is worthless", "Only monks", "Whoever loves his life loses it (John 12:25)."),
("What does light/darkness summary in 12:35–36 echo?", "Johannine ethical urgency — walk while light is here", "New theme", "Contradicts John 1", "Only future light", "Walk while you have the light (John 12:35)."),
("How does Isaiah 53 quotation serve?", "Unbelief was foretold — God's plan includes rejection", "Proves no one sinned", "Cancels prophecy", "Isaiah irrelevant", "Who has believed our report? (John 12:38)."),
("What christological reading of Isaiah does John give?", "Isaiah saw Jesus' glory — NT christological interpretation", "Isaiah saw only a king", "Isaiah is not about Jesus", "Glory is only Shekinah box", "Isaiah… saw his glory and spoke of him (John 12:41)."),
("How does 12:48 connect word and judgment?", "Jesus' words judge at last day — proclamation is serious", "Words do nothing", "Judgment is only works", "No future judgment", "The word that I have spoken will judge him on the last day (John 12:48)."),
("What does Jesus leaving and hiding add?", "Withdrawal until hour — sovereign timing", "Fear alone", "End of ministry", "Failure", "Jesus departed and hid himself from them (John 12:36)."),
("How does \"world has gone after him\" ironically true?", "Gentile seekers and crowd — leaders panic", "No one follows", "World hates Jesus", "Phrase is false", "The world has gone after him (John 12:19)."),
("What does anointing six days before Passover timing suggest?", "Deliberate preparation week — passion nears", "Random date", "Contradicts Synoptics without harmonization", "Only Bethany time", "Six days before Passover (John 12:1)."),
("How does Mary's act relate to later burial anointing stories?", "Thematic continuity — king prepared for tomb", "Contradicts other Gospels", "Only one anointing in history", "John invents", "Kept for burial (John 12:7)."),
("What does crowd's palm branches signify?", "Kingship — festal welcome", "Funeral only", "Farm tools", "Roman tribute", "Took branches of palm trees and went out to meet him (John 12:13)."),
("How does 12:32 universalize mission?", "All peoples drawn — not ethnic limit", "Only Israel", "Drawing is forced", "No one comes", "I will draw all people to myself (John 12:32)."),
("What did Jesus say would happen to those who reject him and do not receive his sayings?", "The word that he has spoken will judge them on the last day", "They will be ignored forever", "They automatically receive life", "Only angels judge", "The word that I have spoken will judge him on the last day (John 12:48)."),
("What did Jesus tell the disciples about the light?", "To walk while they have the light, before darkness overtakes them", "To hide in darkness", "To ignore light", "To wait for night", "Walk while you have the light, lest darkness overtake you (John 12:35)."),
]

_CH13: list[tuple[str, str, str, str, str, str]] = [
("Before what feast did Jesus love his own to the end?", "The Feast of the Passover", "Tabernacles", "Dedication", "Weeks", "Before the Feast of the Passover, Jesus knowing that his hour had come… (John 13:1)."),
("What did Jesus do during supper?", "Rose and laid aside garments and washed disciples' feet", "Preached for three hours", "Blessed bread only", "Left immediately", "Jesus… rose from supper… began to wash the disciples' feet (John 13:2–5)."),
("What did Peter first say when Jesus came to wash his feet?", "You shall never wash my feet", "Wash my head", "I am unworthy", "Use more water", "You shall never wash my feet (John 13:8)."),
("What did Jesus say if Peter did not allow washing?", "He would have no share with him", "He would be richer", "He would be first", "He would be a priest", "If I do not wash you, you have no share with me (John 13:8)."),
("What did Peter then ask Jesus to wash?", "His head and hands also", "Only his sandals", "Nothing", "The floor", "Lord, not my feet only but also my hands and my head (John 13:9)."),
("What did Jesus say the one who ate bread with him would do?", "Lift his heel against him", "Deny him three times only", "Sell him", "Leave early", "He who ate my bread has lifted his heel against me (John 13:18)."),
("Who did the disciples question about whom Jesus meant?", "The beloved disciple next to Jesus", "Peter only", "Thomas", "Judas", "One of his disciples… leaning back against Jesus… (John 13:23–25)."),
("What did Jesus give Judas?", "A morsel of bread", "A bag of silver visible", "A cup", "A scroll", "Dipping the morsel, he gave it to Judas (John 13:26)."),
("What entered Judas when he took the morsel?", "Satan", "Joy", "Peace", "Fear", "After the morsel, then Satan entered into him (John 13:27)."),
("What did Jesus say to Judas?", "What you are going to do, do quickly", "Repent now", "Stay longer", "Give money to the poor", "What you are going to do, do quickly (John 13:27)."),
("What new commandment did Jesus give?", "Love one another as he loved them", "Circumcise converts", "Fast twice weekly", "Pay double tithe", "A new commandment I give to you, that you love one another (John 13:34)."),
("How would people know disciples are Jesus'?", "If they have love for one another", "If they wear a uniform", "If they speak Greek", "If they avoid sinners", "By this all people will know that you are my disciples, if you have love for one another (John 13:35)."),
("Where did Jesus say he was going?", "Where disciples could not come then", "To Rome", "To Egypt", "To the temple only", "Where I am going you cannot come (John 13:33)."),
("What did Jesus predict Peter would do?", "Deny him three times", "Betray him", "Die before Jesus", "Become high priest", "Will you lay down your life for me? … you will deny me three times (John 13:38)."),
("Whom did Jesus say the Father had given all things into whose hands?", "The Son of Man", "Pilate", "Moses", "Caiaphas", "Jesus, knowing that the Father had given all things into his hands (John 13:3)."),
("Theologically, what does foot washing symbolize?", "Humble service and cleansing — pattern of Christ's love", "Only hygiene", "Only ordination", "Only Judas", "If I then, your Lord and Teacher, have washed your feet (John 13:14)."),
("How does Psalm 41 quotation apply to Judas?", "Betrayal by familiar friend — Scripture fulfilled", "Psalm is unrelated", "Judas is innocent", "David wrote only of Saul", "Even my close friend… has lifted his heel against me (John 13:18)."),
("What does love to the end (telos) hint?", "Love complete to the cross — fidelity in hour", "Love ended", "Love failed", "Love is partial", "Having loved his own who were in the world, he loved them to the end (John 13:1)."),
("How does morsel sequence identify betrayer?", "Honor at table turned to treachery — dramatic irony", "Random meal detail", "Judas is honored only", "No betrayer exists", "It is he to whom I will give this morsel of bread (John 13:26)."),
("What does Peter's refusal then excess show?", "Pride then enthusiasm — misunderstanding greatness", "Perfect faith", "No emotion", "He understands servanthood", "You shall never wash my feet… wash my head (John 13:8–9)."),
("How does \"you cannot come\" prepare Farewell Discourse?", "Jesus' departure to Father — disciples must stay", "Jesus excludes disciples forever", "No heaven for disciples", "Only Judas goes", "Where I am going you cannot come (John 13:33)."),
("What ethic does foot washing give leaders?", "Servant pattern — greatness is service", "Wash only feet literally forever", "Leaders rule by fear", "Only slaves wash", "If I then, your Lord and Teacher, have washed your feet (John 13:14)."),
("How does Satan entering Judas after morsel portray?", "Moral responsibility and demonic agency — mystery of evil", "Judas has no blame", "Satan is a metaphor only", "Jesus forces Judas", "Satan entered into him (John 13:27)."),
("What does new commandment \"new\" emphasize?", "New covenant love modeled on Jesus' impending sacrifice", "Old hate command", "Love is optional", "Only for apostles", "A new commandment… as I have loved you (John 13:34)."),
("How does mutual love prove discipleship?", "Visible community witness — apologetic of love", "Love is invisible", "Only miracles prove", "Only creeds prove", "By this all people will know… (John 13:35)."),
("What night is this?", "Night of betrayal — Passover meal context", "Random dinner", "Sabbath lunch", "No timing", "Night when he would depart out of this world (John 13:1)."),
("How does Jesus knowing his hour frame chapter?", "Sovereign love toward cross — not surprised", "Jesus is uncertain", "Hour is wrong", "No plan", "Jesus knowing that his hour had come (John 13:1)."),
("What does laying aside garments prefigure?", "Stripping for cross — servant humility", "Fashion only", "Warmth only", "No cross link", "Laid aside his outer garments (John 13:4)."),
("How does beloved disciple's posture show intimacy?", "Close to Jesus' breast — trusted witness", "Far from Jesus", "Enemy position", "Only symbolic", "Leaning back against Jesus' breast (John 13:25)."),
("What tension exists in Judas leaving?", "Some thought Judas bought feast needs — irony", "Everyone knew betrayal", "Judas stayed", "No one noticed", "Some thought… Judas had the money bag (John 13:29)."),
("How does Peter's boast contrast coming denial?", "Overconfidence — grace needed", "Peter is correct", "Denial is impossible", "Only Judas denies", "I will lay down my life for you (John 13:37)."),
("What does washing feet relate to later Spirit/church?", "Cleansing and mutual care in body of Christ", "Only first century", "Ritual only forever", "Cancelled by Paul", "You ought to wash one another's feet (John 13:14)."),
("Scholarly view: Last Supper timing in John vs Synoptics?", "Harmonizations proposed — theological emphasis on Passover lamb", "All agree easily", "John is wrong", "No scholarship", "Debated; John stresses Passover context differently."),
("How does love command connect to cross next chapters?", "Love as Jesus' life laid down — standard", "Love stops at command", "Cross unrelated", "Love is law only", "As I have loved you (John 13:34)."),
("What does Jesus know about betrayer?", "Identity — sovereign awareness", "Nothing", "Only after act", "Guesses", "Jesus was troubled in spirit… \"Truly… one of you will betray me\" (John 13:21)."),
("How does foot washing answer disciples' rivalry?", "True greatness serves — rebukes power grabs", "Power is goal", "Rivalry is good", "James and John absent", "If I your Lord wash… (John 13:14)."),
("What liturgical echoes might foot washing carry?", "Priestly washings — Jesus as servant high priest", "Pagan baths only", "No OT echoes", "Only Roman customs", "He poured water into a basin (John 13:5)."),
("How does chapter end on denial prediction?", "Foreshadows passion failure and restoration theme", "Ends hope", "Peter is rejected forever", "No restoration", "You will deny me three times (John 13:38)."),
("What does \"having loved his own\" emphasize?", "Particular love for disciples — covenant community", "Only universal with no church", "Only enemies", "Love is generic", "He loved his own who were in the world (John 13:1)."),
("How does Satan's role fit Johannine dualism?", "Light vs darkness — cosmic conflict behind betrayal", "No conflict", "Only political", "Satan is good", "Night… Judas… devil (John 13:2, 27, 30)."),
("What does quick departure of Judas imply?", "Door closed on mercy for that path — narrative speed", "Judas repents", "Jesus chases", "No departure", "Having received the morsel, he immediately went out, and it was night (John 13:30)."),
("What pastoral use does foot washing have?", "Models humility in Christian community — not optional pride", "Only apostles' feet matter", "Humility is weakness", "Washing saves souls alone", "You also ought to wash one another's feet (John 13:14)."),
("How does \"share with me\" language work?", "Covenant fellowship — cleansing and communion", "Financial share", "Land share", "No theology", "You have no share with me (John 13:8)."),
("What does troubled spirit show?", "Jesus' emotional depth before betrayal — true humanity", "Sin", "Surprise", "Coldness", "He was troubled in spirit (John 13:21)."),
("How does morsel honor Judas ironically?", "Guest of honor becomes betrayer — pathos", "Judas is praised by all", "Morsel is poison", "No irony", "It is he to whom I will give this morsel (John 13:26)."),
("What link to Eucharist traditions?", "Bread handed — later church ties to Lord's Supper themes", "John denies supper", "No link ever", "Only baptism", "He dipped the morsel (John 13:26)."),
("How does new commandment fulfill old?", "Leviticus love neighbor fulfilled in Christ-shaped love", "Cancels Old Testament", "Only new with no continuity", "Love neighbor canceled", "Love one another as I have loved you (John 13:34)."),
("What did Jesus know from the beginning about the Twelve?", "Who would betray him", "Nothing", "Only Judas' name", "Only Peter's denial", "He knew who would betray him (John 13:11)."),
("What did Jesus say disciples were if they knew these things?", "Blessed if they do them", "Cursed if they hear", "Neutral", "Only teachers", "If you know these things, blessed are you if you do them (John 13:17)."),
("What did Jesus tell disciples they could not do now?", "Follow him where he was going", "Pray", "Eat", "Read Scripture", "Where I am going you cannot follow me now (John 13:36)."),
]

_CH14: list[tuple[str, str, str, str, str, str]] = [
("What did Jesus say about the Father's house?", "Many rooms; he goes to prepare a place", "One small room", "No place for disciples", "Only angels dwell", "In my Father's house are many rooms… I go to prepare a place for you (John 14:2)."),
("What did Jesus say he would do after preparing a place?", "Come again and take them to himself", "Stay away forever", "Send angels only", "Forget them", "I will come again and will take you to myself (John 14:3)."),
("What did Jesus say he was?", "The way, and the truth, and the life", "The king only", "The temple only", "The law only", "I am the way, and the truth, and the life (John 14:6)."),
("What did Jesus say about coming to the Father?", "No one comes to the Father except through him", "Many ways equally", "Only Moses brings people", "Only priests", "No one comes to the Father except through me (John 14:6)."),
("What did Philip ask Jesus to show?", "The Father", "Rome", "Herod", "Angels only", "Lord, show us the Father, and it is enough for us (John 14:8)."),
("What did Jesus say about seeing him?", "Whoever has seen him has seen the Father", "No one can see him", "Only angels see", "Only after death", "Whoever has seen me has seen the Father (John 14:9)."),
("What did Jesus say about his words and works?", "Believe because of the works", "Ignore works", "Works are evil", "Only words matter", "Believe me… or else believe on account of the works themselves (John 14:11)."),
("What did Jesus promise to ask the Father to give?", "Another Helper", "Money", "A kingdom in Rome", "A new Moses", "I will ask the Father, and he will give you another Helper (John 14:16)."),
("What is the Helper called?", "The Spirit of truth", "The spirit of Rome", "The spirit of fear", "The spirit of sleep", "The Spirit of truth (John 14:17)."),
("Who cannot receive the Spirit?", "The world", "Disciples", "The Father", "Angels", "The world cannot receive him (John 14:17)."),
("What did Jesus leave with disciples?", "Peace — not as the world gives", "Swords", "Money bags", "Fear", "Peace I leave with you; my peace I give to you (John 14:27)."),
("What did Jesus tell disciples not to let their hearts be?", "Troubled or afraid", "Happy", "Silent", "Proud", "Let not your hearts be troubled (John 14:1)."),
("What did Jesus say he who loves him will keep?", "His commandments", "Roman law", "Only dietary rules", "Only Sabbath", "If you love me, you will keep my commandments (John 14:15)."),
("What would the Father do for those who love Jesus?", "Send the Helper", "Ignore them", "Give wealth only", "Remove trials", "My Father will love him, and we will come to him (John 14:23)."),
("What did Jesus say the Helper would teach?", "All things and remind them of Jesus' words", "Greek philosophy", "Roman law", "Nothing", "The Helper… will teach you all things and bring to your remembrance all that I have said (John 14:26)."),
("What did Jesus say about being in the Father and Father in him?", "Mutual indwelling — unity of mission and being", "Separation", "Only metaphor with no reality", "Only human", "Believe me that I am in the Father and the Father is in me (John 14:11)."),
("What greater works would believers do?", "Because Jesus goes to the Father — Spirit-empowered mission", "Greater miracles always physically", "Wealth", "Political power", "Greater works than these will he do, because I am going to the Father (John 14:12)."),
("What did Jesus say about whatever asked in his name?", "He will do it — prayer in Jesus' name", "Nothing happens", "Only material gifts", "Only for apostles", "Whatever you ask in my name, this I will do (John 14:13)."),
("Why would the Father be glorified in the Son?", "Because believers ask in Jesus' name — answered prayer shows Son's mediation", "Father needs fame", "Glory is money", "No mediation", "I will do it, that the Father may be glorified in the Son (John 14:13)."),
("What did Jesus say the ruler of this world had?", "No claim on him", "Full claim", "Ownership", "Victory forever", "The ruler of this world is coming. He has no claim on me (John 14:30)."),
("Theologically, what is \"many rooms\"?", "Assurance of space for every believer — hospitality of God", "Literal hotel", "Only apostles", "Symbolic with no hope", "I go to prepare a place for you (John 14:2)."),
("How is Jesus the way?", "Exclusive mediator — access to Father only through Son", "One path among many", "Way is only morals", "Buddha also", "No one comes to the Father except through me (John 14:6)."),
("What does mutual indwelling of Father and Son mean for Christology?", "Revelation of Father in Son — oneness in mission", "Two gods", "Modalism only", "No relationship", "Believe me that I am in the Father and the Father is in me (John 14:11)."),
("How does Spirit comfort absent Jesus?", "Paraclete continues Jesus' presence and teaching", "Disciples alone", "Spirit replaces Jesus with no continuity", "Spirit is impersonal only", "I will not leave you as orphans; I will come to you (John 14:18)."),
("What does peace not as world mean?", "Kingdom peace — not absence of trouble but presence of Christ", "Worldly ease", "Military victory", "Wealth", "Not as the world gives do I give to you (John 14:27)."),
("How does keeping commandments relate to love?", "Love proves itself in obedience — not mere emotion", "Law saves without faith", "Love needs no obedience", "Only feelings matter", "If you love me, you will keep my commandments (John 14:15)."),
("What does Father and Son make dwelling with believer imply?", "Trinitarian fellowship — God with us", "Only metaphor", "Only future", "Only apostles", "We will come to him and make our home with him (John 14:23)."),
("How does Jesus' going to Father enable Spirit?", "Ascension sends Spirit — Johannine Pentecost linkage", "Spirit ignores Jesus", "No ascension", "Spirit comes before cross", "The Helper… whom the Father will send in my name (John 14:26)."),
("What does \"another\" Helper imply?", "Jesus is first advocate — Spirit continues his work", "Two unrelated helpers", "Jesus failed", "Only human helpers", "Another Helper (John 14:16)."),
("How does troubled heart command fit imminent cross?", "Comfort before crisis — eschatological hope", "Denies crisis", "Trouble is sin", "Only stoicism", "Let not your hearts be troubled (John 14:1)."),
("What christological claim is seeing Father in Son?", "High Christology — revelation of invisible God", "Arianism", "Only human teacher", "Father is visible", "Whoever has seen me has seen the Father (John 14:9)."),
("How does works apologetic function?", "Evidence for faith — signs and words cohere", "Works irrelevant", "Faith without evidence", "Only book knowledge", "Believe… on account of the works (John 14:11)."),
("What does asking in Jesus' name mean?", "Prayer aligned with Jesus' character and mission — not magic formula", "Anything selfish", "Name is charm", "Only Lord's Prayer", "Whatever you ask in my name (John 14:13)."),
("How does ruler of this world have no claim?", "Sinless Son — death is voluntary, not Satan's victory", "Satan owns Jesus", "No spiritual warfare", "Dualism denied", "He has no claim on me (John 14:30)."),
("What does orphan language evoke?", "Israel's hope — God as Father not leaving", "Literal orphans only", "No adoption", "Only OT", "I will not leave you as orphans (John 14:18)."),
("How does love and obedience relate to Pentecost?", "Spirit comes to those who love and obey — readiness", "Spirit ignores obedience", "Only emotion", "Only bishops", "The Spirit… remains with you (John 14:16–17)."),
("Scholarly debate: monotheism and \"I am in Father\"?", "Debates on how John's high Christology fits Jewish monotheism", "All agree polytheism", "No debate", "John is polytheist", "Complexified trinitarian readings."),
("What does preparing a place imply about Jesus' work?", "Heavenly ministry as forerunner — Hebrews theme echo", "No heaven", "Only earthly", "Place is myth", "I go to prepare a place for you (John 14:2)."),
("How does Philip's request reveal misunderstanding?", "Sees Father as separate visually — Jesus corrects revelation", "Philip understands fully", "Father is visible body", "No correction", "Show us the Father (John 14:8)."),
("What does teaching and reminding role of Spirit mean for Scripture?", "Illumination — Spirit authenticates apostolic word", "Spirit contradicts Scripture", "Scripture alone without Spirit", "Only rabbis", "Will remind you of all I said (John 14:26)."),
("How does peace gift prepare for 16:33?", "In me you may have peace — world tribulation", "Peace means no cross", "World is friend", "Tribulation denied", "My peace I give to you (John 14:27)."),
("What does \"little while\" foreshadow?", "Separation then reunion — resurrection joy", "Permanent loss", "Only three hours", "No return", "A little while longer… you will seek me (John 14:19)."),
("How does believing in Jesus relate to believing in Father?", "Mutual belief — to know Jesus is to know Father", "Believe one only", "Father is unknown", "Contradictory", "From now on you do know him and have seen him (John 14:7)."),
("What ethical weight in \"If you loved me, you would rejoice\"?", "Love rejoices at Jesus' return to Father — selfless joy", "Rejoices at loss", "Hates Father", "Only fear", "If you loved me, you would have rejoiced (John 14:28)."),
("How does chapter ground sacramental ecclesiology debates?", "Dwelling and Spirit themes inform church as temple", "Denies church", "Only buildings", "Only invisible", "We will make our home with him (John 14:23)."),
("What does Jesus going away for Helper's coming teach about order?", "Cross and ascension precede Pentecost — salvation history", "Spirit ignores order", "Helper first", "No ascension", "I will ask the Father, and he will give you another Helper (John 14:16)."),
("What did Jesus say the world would not give to the Helper?", "See it or know it", "Money", "A throne", "Scripture", "The world cannot receive him, because it neither sees him nor knows him (John 14:17)."),
("What did Jesus say he would not leave disciples as?", "Orphans", "Kings", "Slaves to Rome", "Pharisees", "I will not leave you as orphans; I will come to you (John 14:18)."),
("What did Jesus say would happen because he lives?", "They would live also", "They would die", "They would remain orphans", "They would rule Rome", "Because I live, you also will live (John 14:19)."),
("On that day what would disciples know?", "That Jesus is in the Father, they in Jesus, and Jesus in them", "Nothing", "Only geography", "Only future prophecy", "On that day you will know that I am in my Father, and you in me, and I in you (John 14:20)."),
]


def ch9_14() -> list[dict]:
    return (
        zip_chapter(9, _CH9)
        + zip_chapter(10, _CH10)
        + zip_chapter(11, _CH11)
        + zip_chapter(12, _CH12)
        + zip_chapter(13, _CH13)
        + zip_chapter(14, _CH14)
    )
