"""Chapters 5–21: 50 questions each (10 × 5 stages), built from curated facts."""
from __future__ import annotations


def U(
    chapter: int,
    stage: int,
    prompt: str,
    correct: str,
    w1: str,
    w2: str,
    w3: str,
    expl: str,
) -> dict:
    return {
        "chapter": chapter,
        "stage": stage,
        "prompt": prompt,
        "correct": correct,
        "wrongs": (w1, w2, w3),
        "explanation": expl,
    }


def _stages_for_50() -> list[int]:
    return [1] * 10 + [2] * 10 + [3] * 10 + [4] * 10 + [5] * 10


def _zip_chapter(ch: int, items: list[tuple[str, str, str, str, str, str]]) -> list[dict]:
    """Each item: (prompt, correct, w1, w2, w3, explanation)."""
    stg = _stages_for_50()
    if len(items) != 50:
        raise ValueError(f"chapter {ch}: expected 50 items, got {len(items)}")
    return [U(ch, stg[i], *items[i]) for i in range(50)]


# --- Chapter 5 ---
def _ch5() -> list[dict]:
    return _zip_chapter(
        5,
        [
            (
                "Beside which pool in Jerusalem did a multitude of the sick lie?",
                "The pool of Bethesda",
                "The pool of Siloam",
                "The pool of Gibeon",
                "The pool of Hebron",
                "In Jerusalem by the Sheep Gate there is a pool called Bethesda (John 5:2).",
            ),
            (
                "How many porches did the pool of Bethesda have?",
                "Five",
                "Three",
                "Seven",
                "Twelve",
                "In these lay a multitude… around the pool — five colonnades (John 5:2).",
            ),
            (
                "How long had the man lying there been ill, according to Jesus?",
                "Thirty-eight years",
                "Twelve years",
                "Seven years",
                "Forty days",
                "The sick man had been there thirty-eight years (John 5:5).",
            ),
            (
                "What did Jesus ask the sick man?",
                "Do you want to be healed?",
                "Who sinned against you?",
                "Will you follow me to Galilee?",
                "Have you kept the whole law?",
                "When Jesus saw him… he said to him, \"Do you want to be healed?\" (John 5:6).",
            ),
            (
                "What did Jesus tell the man to pick up after he was healed?",
                "His mat",
                "His money",
                "His scroll",
                "A stone from the temple",
                "Jesus said to him… \"Pick up your mat, and walk\" (John 5:8).",
            ),
            (
                "On what day did the Jews object that the man was carrying his mat?",
                "The Sabbath",
                "The Passover",
                "The Day of Atonement",
                "A Roman feast day",
                "This was why the Jews were persecuting Jesus, because he was doing things on the Sabbath (John 5:16).",
            ),
            (
                "What excuse did the healed man give for not knowing who healed him?",
                "The crowd was large and Jesus had withdrawn",
                "He was blind",
                "He was asleep",
                "He feared the priests",
                "The man went away and told the Jews it was Jesus who had healed him (John 5:15); earlier he did not know (John 5:13).",
            ),
            (
                "Afterward Jesus found him in the temple and warned him — what else did he say?",
                "Sin no more, that nothing worse may happen to you",
                "Go, sell everything",
                "Return to Bethesda",
                "Bring your offering tomorrow",
                "Jesus found him in the temple… \"See, you are well! Sin no more…\" (John 5:14).",
            ),
            (
                "What did Jesus call God that made the Jews seek all the more to kill him?",
                "His own Father",
                "His commander",
                "The God of Rome",
                "A distant judge",
                "He was even calling God his own Father, making himself equal with God (John 5:18).",
            ),
            (
                "What does the Son do regarding the dead, according to John 5:21?",
                "Raises them up",
                "Leaves them in silence",
                "Sends angels only",
                "Judges only the living",
                "As the Father raises the dead… so the Son gives life to whom he will (John 5:21).",
            ),
            (
                "Who does Jesus say accuses the people, the one in whom they hope?",
                "Moses",
                "Abraham",
                "David",
                "Elijah",
                "There is one who accuses you: Moses, on whom you have set your hope (John 5:45).",
            ),
            (
                "If people believed Moses's writings, whom would they believe?",
                "Jesus",
                "John the Baptist only",
                "The high priest",
                "Caesar",
                "If you believed Moses, you would believe me; for he wrote of me (John 5:46).",
            ),
            (
                "What kind of testimony does Jesus say John gave?",
                "True testimony",
                "False testimony",
                "Symbolic testimony only",
                "Silent testimony",
                "He was a burning and shining lamp, and you were willing to rejoice for a while in his light (John 5:35).",
            ),
            (
                "What does Jesus say the Father has committed to the Son?",
                "All judgment",
                "Only healing",
                "Temple finances",
                "The Sanhedrin's vote",
                "The Father… has given all judgment to the Son (John 5:22).",
            ),
            (
                "Who will hear the voice of the Son of God, according to John 5:25?",
                "The dead",
                "Only angels",
                "Only priests",
                "Only the Pharisees",
                "An hour is coming… when the dead will hear the voice of the Son of God (John 5:25).",
            ),
            (
                "What does Jesus say the Father has life in himself and has granted the Son?",
                "To have life in himself",
                "To inherit land",
                "To abolish the Sabbath",
                "To command armies",
                "As the Father has life in himself, so he has granted the Son also to have life in himself (John 5:26).",
            ),
            (
                "Why does Jesus say his judgment is just?",
                "He seeks not his own will but the will of him who sent him",
                "The crowds approve",
                "Pilate assists him",
                "He ignores evidence",
                "I seek not my own will but the will of him who sent me (John 5:30).",
            ),
            (
                "Besides John, what other witness does Jesus appeal to?",
                "The works the Father gave him to complete",
                "The Roman senate",
                "The temple treasury",
                "Herod's court",
                "The works that the Father has given me to carry out… bear witness about me (John 5:36).",
            ),
            (
                "What does Jesus say the Father who sent him has done?",
                "Borne witness about him",
                "Hidden his identity",
                "Denied him publicly",
                "Left him without the Spirit",
                "The Father who sent me has himself borne witness about me (John 5:37).",
            ),
            (
                "What does Jesus say people have never heard or seen?",
                "The Father's voice or form",
                "The law of Moses",
                "The pool of Bethesda",
                "The Passover lamb",
                "You have neither heard his voice nor seen his form (John 5:37).",
            ),
            (
                "What does Jesus say people search the Scriptures for?",
                "Eternal life",
                "Political power",
                "Genealogies only",
                "Temple blueprints",
                "You search the Scriptures because you think that in them you have eternal life (John 5:39).",
            ),
            (
                "What does Jesus say the Scriptures do?",
                "Bear witness about him",
                "Replace faith",
                "Contradict Moses",
                "End at Malachi with no hope",
                "They bear witness about me (John 5:39).",
            ),
            (
                "The man by Bethesda had no one to do what when the water was stirred?",
                "Put him into the pool",
                "Bring him food",
                "Carry his mat beforehand",
                "Read the law to him",
                "I have no one to put me into the pool when the water is stirred up (John 5:7).",
            ),
            (
                "What did the Jews tell the man he was not allowed to do on the Sabbath?",
                "Carry his mat",
                "Pray",
                "Speak Jesus' name",
                "Enter the temple",
                "It is the Sabbath, and it is not lawful for you to take up your bed (John 5:10).",
            ),
            (
                "What did the healed man say Jesus told him?",
                "Take up your bed and walk",
                "Stay in bed another week",
                "Wash in Siloam",
                "Bring two doves",
                "The man who healed me… said, \"Take up your bed, and walk\" (John 5:11–12).",
            ),
            (
                "Why did the Jews persecute Jesus, according to John 5:16?",
                "He was doing these things on the Sabbath",
                "He avoided Jerusalem",
                "He refused to baptize",
                "He denied Moses",
                "This was why the Jews were persecuting Jesus, because he was doing these things on the Sabbath.",
            ),
            (
                "What defense does Jesus give for working on the Sabbath?",
                "My Father is working until now, and I am working",
                "The Sabbath is abolished",
                "Rome permits it",
                "Emergencies excuse everyone",
                "My Father is working until now, and I am working (John 5:17).",
            ),
            (
                "The Father has given the Son authority to execute judgment because he is whom?",
                "The Son of Man",
                "A Levite",
                "A Roman citizen",
                "The high priest's assistant",
                "He is the Son of Man (John 5:27).",
            ),
            (
                "What hour does Jesus say is coming and now is?",
                "When the dead will hear the voice of the Son of God",
                "When Rome falls",
                "When the temple triples in size",
                "When Moses returns",
                "An hour is coming and is now here, when the dead will hear the voice of the Son of God (John 5:25).",
            ),
            (
                "What does Jesus say he does not accept from people?",
                "Glory from man",
                "Offerings",
                "Prayers",
                "Children",
                "I do not receive glory from people (John 5:41).",
            ),
            (
                "What does Jesus say would prove people love God?",
                "If they received the one God sent",
                "If they built larger synagogues",
                "If they defeated Rome",
                "If they memorized genealogies",
                "If you received me, you would receive him who sent me (cf. John 5:43).",
            ),
            (
                "Theologically, why is Jesus' claim to be Son with divine prerogatives central to John 5?",
                "It reveals his unity with the Father in works, life-giving, and judgment",
                "It is a minor title",
                "It denies monotheism entirely",
                "It refers only to adoption like kings",
                "The chapter unpacks Son-Father unity in mission and authority.",
            ),
            (
                "How does the healing at Bethesda function as a \"sign\" in context?",
                "It provokes controversy about Sabbath and Jesus' identity as life-giver",
                "It ends all conflict",
                "It is ignored by John",
                "It proves only medical skill",
                "The miracle launches the discourse on Jesus' authority (John 5:1–18).",
            ),
            (
                "What does the discourse on witnesses contribute to Johannine legal imagery?",
                "Jesus meets standards of testimony through multiple converging witnesses",
                "Courts are irrelevant",
                "Only one witness is allowed",
                "Testimony is impossible",
                "John, works, Father, and Scripture testify (John 5:31–47).",
            ),
            (
                "Why might John stress that Jesus found the man in the temple after healing?",
                "It links physical restoration to spiritual warning — sin still matters",
                "The temple was the only dry place",
                "Jesus needed directions",
                "The man was a priest",
                "Jesus speaks of holiness after healing (John 5:14).",
            ),
            (
                "How does John 5:24 describe the believer's present state?",
                "Passed from death to life — will not come into judgment",
                "Still condemned until heaven",
                "Uncertain until works are counted",
                "Judged every Sabbath",
                "Whoever hears my word and believes… has passed from death to life (John 5:24).",
            ),
            (
                "What role does \"honor\" play in John 5:23?",
                "Honoring the Son honors the Father; dishonoring the Son dishonors the Father",
                "Honor is only cultural",
                "The Son needs no honor",
                "Honor applies only to angels",
                "All may honor the Son just as they honor the Father (John 5:23).",
            ),
            (
                "How does Jesus' use of \"Son of Man\" in judgment (John 5:27) echo Danielic themes?",
                "The Son of Man receives kingdom and authority — here, authority to judge",
                "It denies Daniel",
                "Son of Man means only human",
                "It refers to Ezekiel only",
                "Daniel's Son of Man is evoked in judicial authority.",
            ),
            (
                "What is ironic about the Jews' confidence in Moses while rejecting Jesus?",
                "Moses wrote of Jesus — their hope undermines their unbelief",
                "Moses opposed Jesus",
                "Moses never wrote Scripture",
                "Irony is absent",
                "If you believed Moses, you would believe me (John 5:46).",
            ),
            (
                "How does John 5 prepare for later trials before the Sanhedrin and Pilate?",
                "Themes of testimony, judgment, and Jesus' unity with the Father recur at the Passion",
                "Chapter 5 ignores law",
                "No witnesses appear later",
                "Pilate is absent from John",
                "Legal language in John 5 foreshadows the trial narratives.",
            ),
            (
                "What does Jesus imply by saying people do not have the word of God abiding in them?",
                "They reject the one whom God sent — Scripture's witness fails in them",
                "They memorize too much",
                "God's word is only oral",
                "The word is only for Gentiles",
                "If you do not believe his writings, how will you believe my words? (John 5:47).",
            ),
            (
                "Scholars connect Bethesda's stirred water with what background?",
                "Popular hope for angelic/agency healing — Jesus replaces the pool's promise with his word",
                "Roman plumbing codes",
                "Pagan oracles only",
                "Siloam's architecture",
                "The stirring of the water sets up Jesus as true healer (John 5:4 textual note in some MSS).",
            ),
            (
                "How does John 5:29's resurrection to life vs. judgment cohere with John's overall eschatology?",
                "Present spiritual resurrection and future bodily resurrection both appear in John's thought",
                "Only past matters",
                "Resurrection is metaphor with no future",
                "Judgment is canceled",
                "Hour is coming when all in tombs will hear his voice (John 5:28–29).",
            ),
            (
                "What christological peak does John 5:18 reach in the Jews' reaction?",
                "Making himself equal with God — John's readers see the charge clearly stated",
                "They think he is only a prophet",
                "They ignore him",
                "They agree with him",
                "He was… calling God his own Father, making himself equal with God (John 5:18).",
            ),
            (
                "How does the Father's witness (John 5:37) relate to later voice from heaven in John?",
                "It anticipates the Father's audible testimony to the Son at Jesus' baptism and glory",
                "The Father never speaks",
                "Only the Son speaks",
                "Thunder is unrelated",
                "The Father bears witness to the Son in the Gospel narrative.",
            ),
            (
                "What ethical issue does the healed man's blame of \"no man\" (John 5:7) subtly raise?",
                "Human helplessness apart from Christ's initiative — grace must come to us",
                "Self-help is all we need",
                "The pool is unnecessary",
                "Blame is always sinful",
                "The man's helplessness parallels spiritual need for Christ's word.",
            ),
            (
                "How might John 5's debate on Sabbath relate to Jesus as Lord of the Sabbath?",
                "The Son's work aligns with the Father's ongoing work — rest in God, not mere cessation",
                "Sabbath is abolished without trace",
                "Jesus breaks God's law",
                "Sabbath applies only to farmers",
                "My Father is working until now, and I am working (John 5:17).",
            ),
            (
                "What does the unity of will between Father and Son in John 5:19–20 teach about trinitarian relations?",
                "The Son does nothing of himself but what he sees the Father doing — mutual indwelling mission",
                "The Son acts alone",
                "The Father is unaware",
                "Two separate gods",
                "The Son can do nothing of his own accord (John 5:19).",
            ),
            (
                "How does John 5:44 expose the barrier to faith?",
                "Seeking glory from one another while not seeking the glory from God",
                "Seeking too little honor",
                "Avoiding the synagogue",
                "Loving Rome's glory",
                "How can you believe, when you receive glory from one another? (John 5:44).",
            ),
            (
                "What does Jesus ask at the end of his argument about Moses's writings?",
                "If you do not believe his writings, how will you believe my words?",
                "Why do you read at all?",
                "Who wrote Genesis?",
                "Will you study Greek?",
                "If you do not believe his writings, how will you believe my words? (John 5:47).",
            ),
        ],
    )


import john_quiz_specs_ch06_21 as _rest


def all_questions() -> list[dict]:
    return _ch5() + _rest.all_chapters()
