"""Chapter 4 — Samaritan woman, official's son; 10 questions × 5 stages."""
from __future__ import annotations


def mk(
    st: int,
    prompt: str,
    correct: str,
    w1: str,
    w2: str,
    w3: str,
    expl: str,
) -> dict:
    return {
        "chapter": 4,
        "stage": st,
        "prompt": prompt,
        "correct": correct,
        "wrongs": (w1, w2, w3),
        "explanation": expl,
    }


def questions() -> list[dict]:
    return [
        # Stage 1 — direct recall
        mk(
            1,
            "Through what region did Jesus travel when going from Judea toward Galilee in John 4?",
            "Samaria",
            "The Decapolis",
            "Idumea",
            "Perea",
            "Jesus had to go through Samaria (John 4:4).",
        ),
        mk(
            1,
            "What Samaritan town did Jesus come to in John 4?",
            "Sychar",
            "Capernaum",
            "Jericho",
            "Bethany",
            "He came to a town of Samaria called Sychar (John 4:5).",
        ),
        mk(
            1,
            "Near what landmark did Jesus sit down, tired from his journey?",
            "Jacob's well",
            "The pool of Bethesda",
            "The temple treasury",
            "The Mount of Olives",
            "Jacob's well was there (John 4:6).",
        ),
        mk(
            1,
            "What did Jesus ask the Samaritan woman for when they met?",
            "Give me a drink",
            "Tell me your name",
            "Show me the city",
            "Bring your husband here first",
            "Jesus said to her, \"Give me a drink\" (John 4:7).",
        ),
        mk(
            1,
            "What did Jesus offer that would become in the one who receives it \"a spring of water welling up to eternal life\"?",
            "Living water",
            "The kingdom",
            "A new law",
            "The Spirit alone, with no image of water",
            "Jesus speaks of living water (John 4:10–14).",
        ),
        mk(
            1,
            "How many husbands did Jesus say the woman had had?",
            "Five",
            "Three",
            "Seven",
            "One",
            "\"For you have had five husbands\" (John 4:18).",
        ),
        mk(
            1,
            "What did Jesus say about the man the woman was then living with?",
            "He was not her husband",
            "He was her lawful husband",
            "He was a priest",
            "John does not say",
            "\"The one you now have is not your husband\" (John 4:18).",
        ),
        mk(
            1,
            "What did Jesus say to the woman when she spoke of the Messiah coming?",
            "I who speak to you am he",
            "You must wait longer",
            "The Messiah will be from Jerusalem",
            "No one can know yet",
            "Jesus said to her, \"I who speak to you am he\" (John 4:26).",
        ),
        mk(
            1,
            "What did the Samaritans from Sychar urge Jesus to do after they believed?",
            "Stay with them",
            "Leave at once",
            "Go to Jerusalem",
            "Baptize them in the Jordan",
            "They asked him to stay with them, and he stayed two days (John 4:40).",
        ),
        mk(
            1,
            "The official's son was healed in Capernaum at what hour, according to his servants?",
            "The seventh hour",
            "The third hour",
            "The sixth hour",
            "At sunset",
            "The fever left him at the seventh hour (John 4:52–53).",
        ),
        # Stage 2 — narrative detail
        mk(
            2,
            "Why did Jesus leave Judea and head toward Galilee, according to John 4:1–3?",
            "The Pharisees heard Jesus was making more disciples and baptizing",
            "The Romans expelled him",
            "John the Baptist sent him away",
            "A famine struck Judea",
            "Jesus left because Pharisees heard he was gaining more disciples than John (John 4:1–3).",
        ),
        mk(
            2,
            "What did the Samaritan woman note about Jews and Samaritans regarding water?",
            "Jews have no dealings with Samaritans",
            "Jews never drink water",
            "Samaritans refuse cups",
            "Only priests may draw water",
            "She said Jews have no dealings with Samaritans (John 4:9).",
        ),
        mk(
            2,
            "If the woman knew the gift of God and who was asking, what would Jesus have given her?",
            "Living water",
            "Gold",
            "A position in the synagogue",
            "A written certificate of divorce",
            "He would have given her living water (John 4:10).",
        ),
        mk(
            2,
            "Where did the disciples go while Jesus talked with the woman?",
            "Into the town to buy food",
            "To the Jordan to baptize",
            "To Jerusalem for the feast",
            "To pray on a mountain",
            "The disciples had gone away into the city to buy food (John 4:8).",
        ),
        mk(
            2,
            "What did Jesus tell his disciples his food was?",
            "To do the will of him who sent him and finish his work",
            "Bread and fish they would buy",
            "The Passover lamb",
            "Fasting until evening",
            "My food is to do the will of him who sent me (John 4:34).",
        ),
        mk(
            2,
            "What did many Samaritans believe first — before hearing Jesus themselves?",
            "The woman's word about Jesus",
            "Only the disciples' preaching",
            "A sign in the sky",
            "The Pharisees' report",
            "They believed because of the woman's testimony (John 4:39).",
        ),
        mk(
            2,
            "How did the royal official first approach Jesus in Cana?",
            "He asked Jesus to come down before his child died",
            "He sent a servant secretly",
            "He demanded a sign first",
            "He refused to speak to Jesus",
            "He begged Jesus to come down to Capernaum (John 4:47).",
        ),
        mk(
            2,
            "What did Jesus tell the official after the official pleaded again?",
            "Go; your son will live",
            "Your faith is too weak",
            "Bring your wife first",
            "Wait three days",
            "Jesus said, \"Go; your son will live\" (John 4:50).",
        ),
        mk(
            2,
            "When the official found out the hour the boy recovered, what did he do?",
            "He believed, and his whole household",
            "He doubted",
            "He reported Jesus to the priests",
            "He kept it secret",
            "The man believed the word that Jesus spoke to him (John 4:53).",
        ),
        mk(
            2,
            "John calls the healing of the official's son the second sign. When did Jesus do it?",
            "After he came from Judea to Galilee",
            "During the Passover in Jerusalem",
            "Before the wedding at Cana",
            "On the Sabbath in Capernaum",
            "This was the second sign Jesus did when he had come from Judea to Galilee (John 4:54).",
        ),
        # Stage 3 — interpretation
        mk(
            3,
            "What does Jesus mean that worship will be \"in spirit and truth\" (John 4:23–24)?",
            "True worship is not tied to one mountain but is spiritual and sincere, matching God's nature",
            "Worship is only private emotion",
            "Worship requires a physical temple",
            "Spirit refers only to the wind",
            "God is spirit, and his worshipers must worship in spirit and truth.",
        ),
        mk(
            3,
            "Why is the woman's progressive recognition of Jesus (from Jew to prophet to Messiah) significant?",
            "It shows deepening understanding as revelation unfolds — a model of coming to faith",
            "It shows she was confused the whole time",
            "John thinks titles do not matter",
            "She never changes her mind",
            "Her titles for Jesus escalate as the conversation deepens.",
        ),
        mk(
            3,
            "What does the \"harvest\" language in John 4:35–38 imply about mission?",
            "The fields are ready; others labored and disciples enter their work",
            "Farming is the main metaphor for salvation",
            "Only apostles may evangelize",
            "Harvest means the final judgment only",
            "Jesus says the fields are white for harvest — urgency in gospel labor.",
        ),
        mk(
            3,
            "How does the Samaritan woman's witness function in John 4?",
            "She becomes an evangelist to her town, drawing many to Jesus",
            "She is silenced by the disciples",
            "She denies Jesus afterward",
            "Her role is only negative example",
            "Many Samaritans believed because of her word (John 4:39).",
        ),
        mk(
            3,
            "What contrast does John set up between Nicodemus (John 3) and the Samaritan woman?",
            "Respected male teacher at night vs. marginalized woman at midday — both encounter Jesus",
            "Both reject Jesus",
            "Nicodemus is more sinful",
            "John prefers male inquirers",
            "Contrasting social status and setting highlights who receives revelation.",
        ),
        mk(
            3,
            "What does Jesus reveal about the woman's past that shows his knowledge?",
            "Her marital history — five husbands and current man not her husband",
            "Her income",
            "Her children's names",
            "Her secret sins in Samaria's temple",
            "Jesus speaks of her husbands though she had not told him (John 4:18).",
        ),
        mk(
            3,
            "In John 4:10, what is the \"gift of God\" Jesus refers to?",
            "The salvation and Spirit symbolized by living water — God's gracious offer",
            "The temple tax exemption",
            "Land in Canaan",
            "A royal title",
            "The context ties the gift to the living water Jesus gives.",
        ),
        mk(
            3,
            "Why might John include the detail that disciples were amazed Jesus spoke with a woman?",
            "It shows cultural taboo and Jesus's willingness to dignify the marginalized",
            "It means the woman was a teacher",
            "It shows the disciples approved immediately",
            "It is only historical trivia",
            "They marveled that he was talking with a woman (John 4:27).",
        ),
        mk(
            3,
            "What does the official's faith in Jesus' word without seeing the miracle first illustrate?",
            "Faith resting on Jesus' word — the healing confirms what he already trusted",
            "Faith without evidence is wrong",
            "The official never believed",
            "Miracles alone create faith",
            "The man believed the word Jesus spoke before he confirmed the hour (John 4:50–53).",
        ),
        mk(
            3,
            "What theme connects the living water discourse and the son's healing?",
            "Jesus' word gives life — spiritually and physically",
            "Water and sickness are unrelated in John",
            "Only Gentiles get signs",
            "Signs always fail",
            "Both stories show life coming through Jesus' word.",
        ),
        # Stage 4 — deeper synthesis
        mk(
            4,
            "How does John 4:24 (\"God is spirit\") inform Jesus' claim about true worship?",
            "Worship must match God's spiritual being, not merely external place or form",
            "God has a physical body like humans",
            "Worship is optional for believers",
            "Spirit denies the body",
            "Because God is spirit, worship must be in spirit and truth.",
        ),
        mk(
            4,
            "How does Jesus' knowledge of the woman's life function theologically in John?",
            "It displays divine insight, preparing for fuller revelation of his identity",
            "It proves only prophets know the past",
            "It shames her without purpose",
            "It shows Jesus guessed",
            "Prophetic knowledge points to who Jesus is.",
        ),
        mk(
            4,
            "What Old Testament backdrop enriches Jesus' offer of \"living water\"?",
            "Jeremiah's living waters, Ezekiel's river — eschatological hope of renewal",
            "Only Greek philosophy",
            "No Old Testament connection",
            "The bronze serpent only",
            "John's readers would hear OT echoes of water and new covenant renewal.",
        ),
        mk(
            4,
            "Why is the Samaritan mission significant in John's narrative of Jesus?",
            "It shows salvation is not limited to Judean expectations; Gentile-adjacent Samaritans respond in faith",
            "It cancels Jewish mission",
            "It proves Samaritans are Israel",
            "It replaces Galilee",
            "Many Samaritans believe — a widening circle of witness.",
        ),
        mk(
            4,
            "How does the \"fields are white for harvest\" saying relate to John's view of Jesus' hour?",
            "Urgency — the time of salvation fruitfulness is already present in Jesus' ministry",
            "Harvest means delay",
            "Jesus refuses disciples' help",
            "Agriculture replaces theology",
            "Jesus urges eyes for the ready harvest (John 4:35).",
        ),
        mk(
            4,
            "Compare the faith of the Samaritan townspeople with the official in Capernaum.",
            "Both respond to Jesus' word with belief — communal and household faith",
            "Both reject Jesus",
            "Only the official has faith",
            "Samaritans never hear Jesus",
            "Samaritans believe Jesus' word; the official's whole household believes (John 4:39–53).",
        ),
        mk(
            4,
            "What does John communicate by placing this chapter between Nicodemus and Bethesda?",
            "A sequence of widening revelation: rabbi, woman, then sick man — Jesus as Savior of all kinds",
            "Random travel narrative",
            "Samaria is filler",
            "John ignores geography",
            "Literary placement shows different audiences encountering Christ.",
        ),
        mk(
            4,
            "In what sense is Jesus' thirst at the well both human and rhetorical?",
            "He is truly human (asks for water) yet offers what only he can give (living water)",
            "He was not really thirsty",
            "Thirst proves he sinned",
            "Rhetoric replaces history",
            "Real thirst opens the dialogue that reveals his deeper offer.",
        ),
        mk(
            4,
            "How does the woman's question about Mount Gerizim vs. Jerusalem advance John's theology?",
            "It lets Jesus declare a new era of Spirit-and-truth worship beyond localized shrines",
            "It proves Gerizim is correct",
            "It denies the Old Testament",
            "It is only political",
            "Jesus transcends the old debate by redefining worship around God's nature.",
        ),
        mk(
            4,
            "What did the Samaritan woman leave behind when she went into town to tell others about Jesus?",
            "Her water jar",
            "Her money bag",
            "Her scroll of the law",
            "Her cloak",
            "The woman left her water jar and went away into town (John 4:28).",
        ),
        # Stage 5 — advanced
        mk(
            5,
            "Scholars often connect John 4's living water to what prophetic hope?",
            "Ezekiel 36–37 and Joel 2 — Spirit poured out, new covenant life",
            "Only Daniel's beasts",
            "Solomon's proverbs exclusively",
            "The law of Moses alone",
            "Living water fits OT expectation of eschatological renewal.",
        ),
        mk(
            5,
            "What christological claim is implicit when Jesus says worship must be \"in truth\"?",
            "He is the truth — worship is oriented to the Father through the revealing Son",
            "Truth is subjective only",
            "Truth opposes love",
            "Truth is a place in Samaria",
            "Truth language in John centers on Jesus (14:6).",
        ),
        mk(
            5,
            "How does the Samaritan woman's five husbands function beyond mere scandal?",
            "It illustrates spiritual thirst and misplaced hopes that Jesus addresses",
            "It only condemns her permanently",
            "John counts husbands literally with no meaning",
            "It proves polygamy is blessed",
            "The detail exposes need that Jesus meets with living water.",
        ),
        mk(
            5,
            "What missional pattern appears in John 4:38 (others labored, you enter)?",
            "Continuity of gospel labor across witnesses — John the Baptist, Jesus, disciples",
            "Only one generation may preach",
            "Labor means paid work only",
            "Disciples replace Jesus completely",
            "Jesus honors preparatory witness and present harvest.",
        ),
        mk(
            5,
            "How does John 4 prepare for the bread-of-life discourse in John 6?",
            "Both chapters present Jesus as the source of life believers must receive by faith",
            "They contradict each other",
            "Chapter 4 ignores belief",
            "Water and bread are unrelated symbols",
            "Living water anticipates Jesus as life-giver like the bread from heaven.",
        ),
        mk(
            5,
            "What does the healing-at-distance of the official's son contribute to John's sign theology?",
            "It shows Jesus' word is effective apart from presence — authority over space and death",
            "It proves Jesus feared Capernaum",
            "Signs are tricks",
            "Distance cancels miracles",
            "The boy is healed without Jesus being in Capernaum (John 4:50–53).",
        ),
        mk(
            5,
            "In Johannine terms, how does \"the Father seeks worshipers\" (John 4:23) relate to election and mission?",
            "God actively draws people to true worship — mission participates in the Father's seeking",
            "God is passive",
            "Seeking refers only to animals",
            "Worshipers are automatic",
            "The Father seeks true worshipers in spirit and truth.",
        ),
        mk(
            5,
            "Why might John stress Jesus was \"wearied\" from the journey (John 4:6)?",
            "It affirms true incarnation — the Son shares our weakness while giving life",
            "It implies Jesus sinned by tiredness",
            "It denies his divinity",
            "Weariness is metaphor only with no reality",
            "True humanity is foundational for John's high Christology.",
        ),
        mk(
            5,
            "How does the two-day stay with Samaritans foreshadow later Gentile inclusion in Acts?",
            "Jesus' welcome among Samaritans anticipates the church's cross-cultural expansion",
            "It forbids preaching to Gentiles",
            "It ends Jewish mission",
            "Samaritans are not Gentiles",
            "Jewish Messiah dwelling with Samaritans hints at broader salvation.",
        ),
        mk(
            5,
            "What did the Samaritans say about Jesus after hearing him themselves (John 4:42)?",
            "They knew he was truly the Savior of the world",
            "They knew he was only a Jewish prophet",
            "They knew he was the Roman emperor",
            "They knew he was Elijah returned",
            "We know that this is indeed the Savior of the world (John 4:42).",
        ),
    ]
