"""Gap fill: chapters 1–3 to reach 10 questions per stage (50 total)."""
from __future__ import annotations


def g(
    chapter: int,
    stage: int,
    prompt: str,
    correct: str,
    w1: str,
    w2: str,
    w3: str,
    expl: str,
) -> dict:
    return {
        "chapter": chapter,
        "stage": stage,
        "prompt": prompt,
        "correct": correct,
        "wrongs": (w1, w2, w3),
        "explanation": expl,
    }


def questions() -> list[dict]:
    return [
        # Ch1 stages 3–5 (+5 each)
        g(
            1,
            3,
            "John 1:14 says the Word became flesh and dwelt among us. What did the disciples behold?",
            "His glory",
            "Only his humility",
            "Angels only",
            "The temple veil",
            "They saw his glory, glory as of the only Son from the Father (John 1:14).",
        ),
        g(
            1,
            3,
            "According to John 1:16, from whose fullness did believers receive grace?",
            "From the Word's fullness",
            "From Moses alone",
            "From the temple",
            "From John the Baptist's baptism",
            "\"From his fullness we have all received, grace upon grace\" (John 1:16).",
        ),
        g(
            1,
            3,
            "What contrast does John 1:17 draw between Moses and Jesus Christ?",
            "The law was given through Moses; grace and truth came through Jesus Christ",
            "Moses gave grace; Jesus gave law",
            "Both gave only law",
            "Neither Moses nor Jesus gave law",
            "Grace and truth came through Jesus Christ (John 1:17).",
        ),
        g(
            1,
            3,
            "Who is said in John 1:18 to have made the Father known?",
            "The only God, who is at the Father's side",
            "Moses",
            "Elijah",
            "The high priest",
            "The only God, who is at the Father's side, has made him known (John 1:18).",
        ),
        g(
            1,
            3,
            "What did John the Baptist say he was not worthy to do regarding the one coming after him?",
            "Untie the strap of his sandal",
            "Sit at his right hand",
            "Baptize him",
            "Name him publicly",
            "John said he was not worthy to untie the strap of his sandal (John 1:27).",
        ),
        g(
            1,
            4,
            "Why does John stress that the Baptist was not the light (John 1:8)?",
            "So no one would confuse the witness with the Messiah, who is the true light",
            "Because the Baptist was sinful",
            "Because light is only a metaphor with no person",
            "To criticize the Baptist",
            "He was not the light, but came to bear witness about the light (John 1:8).",
        ),
        g(
            1,
            4,
            "How does \"the Word was God\" (John 1:1) relate to \"the Word was with God\"?",
            "It distinguishes persons within the Godhead while affirming full deity of the Word",
            "It means two separate gods",
            "It contradicts monotheism",
            "It refers only to a human messenger",
            "The Word is distinct from the Father yet fully God.",
        ),
        g(
            1,
            4,
            "What is the significance of \"we have seen his glory\" in connection with the Exodus?",
            "Glory language recalls the tabernacle; Jesus is the dwelling of God among us",
            "It denies the Old Testament",
            "It refers only to future glory",
            "It means only angels saw him",
            "The Word tabernacled among us as God's presence once dwelt with Israel.",
        ),
        g(
            1,
            4,
            "Why might John begin with \"In the beginning\" echoing Genesis?",
            "To present Jesus as the agent of creation and of the new creation",
            "To replace Genesis",
            "To discuss only chronology",
            "To introduce John the Baptist first",
            "Echoing Genesis 1:1 frames Jesus as central to creation and redemption.",
        ),
        g(
            1,
            4,
            "What does the Baptist's denial sequence (not Christ, Elijah, the Prophet) accomplish narratively?",
            "It clears false identities so Jesus can be recognized as the Lamb and Son",
            "It proves the Baptist lied",
            "It shows no Messiah is expected",
            "It replaces Jesus with the Prophet",
            "John eliminates wrong categories pointing to Jesus.",
        ),
        g(
            1,
            5,
            "Discuss the Greek term logos as John uses it. What primary OT and Hellenistic backgrounds inform it?",
            "God's creative word and wisdom; John's readers would hear both divine agency and personhood",
            "Only Greek philosophy with no Jewish input",
            "Only human speech",
            "A title for Caesar only",
            "Logos connects to God's powerful speech in creation and wisdom traditions.",
        ),
        g(
            1,
            5,
            "How does John 1:13 guard the doctrine of regeneration?",
            "Birth as God's children is not by human blood, flesh, or will, but by God's will",
            "It says birth is only physical",
            "It denies new birth",
            "It attributes birth to the synagogue",
            "Spiritual birth is wholly from God (John 1:13).",
        ),
        g(
            1,
            5,
            "What role does eyewitness language (\"we have seen\") play in John's epistemology of faith?",
            "It ties theological claims to apostolic testimony — faith rests on witnessed revelation",
            "It rejects history",
            "It means only one apostle saw",
            "It is purely mythic",
            "The Prologue grounds claims in witness (John 1:14).",
        ),
        g(
            1,
            5,
            "How does the Lamb of God title in John 1:29 connect to Passover and Isaiah's suffering servant?",
            "It evokes sacrificial atonement and the Lord's servant who bears sin",
            "It refers only to a gentle animal",
            "It cancels Old Testament sacrifice",
            "It is only a nickname",
            "Lamb imagery carries OT sacrificial and servant strands.",
        ),
        g(
            1,
            5,
            "What ecclesiological hint appears in Peter being renamed Cephas (rock)?",
            "Though developed later, naming anticipates Peter's foundational role among disciples",
            "It means Peter replaces Jesus",
            "It is a joke",
            "It refers to geology only",
            "Jesus renames Simon as part of calling his community (John 1:42).",
        ),
        # Ch2 +18
        g(
            2,
            3,
            "What does John mean that Jesus \"manifested his glory\" at Cana (John 2:11)?",
            "The miracle revealed Jesus' divine identity and power to his disciples",
            "It was only a party trick",
            "Glory means only human fame",
            "John denies signs reveal anything",
            "The first sign manifested his glory so disciples believed (John 2:11).",
        ),
        g(
            2,
            3,
            "How does the temple cleansing relate to Jesus' claim about raising the temple in three days?",
            "His body is the true temple; his resurrection will prove his authority over the old system",
            "It means Herod's building project",
            "It denies resurrection",
            "It is about destroying Jerusalem only",
            "Jesus spoke of the temple of his body (John 2:21).",
        ),
        g(
            2,
            3,
            "Why does John say Jesus did not entrust himself to those who believed because he knew all people?",
            "True faith must be deeper than signs — Jesus discerns genuine trust",
            "He distrusted everyone equally",
            "He wanted fewer followers",
            "He did not know hearts",
            "He knew what was in man — superficial faith is not enough (John 2:24–25).",
        ),
        g(
            2,
            3,
            "What does the master of the feast not knowing where the wine came from illustrate?",
            "Jesus' work can be unrecognized by authorities while disciples know the source",
            "The master was dishonest",
            "Wine is irrelevant",
            "Disciples were ignorant",
            "The servants knew; the master did not — selective knowledge in the story (John 2:9).",
        ),
        g(
            2,
            3,
            "How is Mary portrayed when she tells Jesus, \"They have no wine\"?",
            "As bringing a need to Jesus, while his \"hour\" remains his Father's timing",
            "As commanding Jesus",
            "As opposing the wedding",
            "As unaware of Jesus' identity",
            "Mary presents the need; Jesus responds on his own terms (John 2:3–4).",
        ),
        g(
            2,
            4,
            "What theological pattern appears in Jesus' first sign being at a wedding?",
            "Messianic joy and new covenant blessing — wine and feast imagery of the kingdom",
            "Marriage is the main topic of John",
            "Jesus opposed weddings",
            "Signs are random",
            "Cana begins a series of signs revealing who Jesus is.",
        ),
        g(
            2,
            4,
            "How does John 2 connect Jesus' zeal for his Father's house to Psalm 69?",
            "Zeal for God's house consumes him — Scripture is fulfilled in his cleansing action",
            "Psalm 69 is unrelated",
            "Jesus misquoted Scripture",
            "The disciples invented the connection",
            "His disciples remembered Scripture after resurrection (John 2:17).",
        ),
        g(
            2,
            4,
            "What does \"destroy this temple\" reveal about Jewish misunderstanding of Jesus' mission?",
            "They took him literally about Herod's building, missing his bodily resurrection",
            "They understood perfectly",
            "They cared only about money",
            "They wanted to help build",
            "They spoke of Herod's temple; Jesus meant his body (John 2:20–21).",
        ),
        g(
            2,
            4,
            "Why does John mention the disciples later remembered Jesus' words?",
            "It shows progressive understanding — resurrection clarifies his words",
            "It means disciples forgot everything",
            "Memory is unimportant in John",
            "Only enemies remembered",
            "After he was raised, they remembered (John 2:22).",
        ),
        g(
            2,
            4,
            "How does the sign at Cana function as a \"sign\" in Johannine theology?",
            "It points beyond itself to Jesus' identity and evokes faith",
            "Signs replace preaching",
            "Signs are ends in themselves",
            "John rejects signs",
            "This, the first of his signs, manifested his glory (John 2:11).",
        ),
        g(
            2,
            5,
            "What textual links connect the six stone jars for Jewish rites of purification to Johannine themes?",
            "They tie Jesus' sign to cultic washings he transforms into messianic abundance",
            "They prove Judaism is abolished in one verse",
            "They are decorative detail only",
            "They refer to pagan rites",
            "The jars were for the Jewish rites of purification (John 2:6).",
        ),
        g(
            2,
            5,
            "How might the abundance of wine (120–180 gallons) function symbolically?",
            "It signals extravagant grace — the kingdom's joy exceeds expectations",
            "It encourages drunkenness",
            "It is a math error",
            "It means little wine was needed",
            "Extravagant quantity fits messianic banquet imagery.",
        ),
        g(
            2,
            5,
            "In what sense is the temple cleansing a public act unlike the private Cana sign?",
            "It confronts the religious establishment and claims authority over sacred space",
            "It was secret",
            "It avoided Jerusalem",
            "It pleased the chief priests",
            "Jesus drove out sellers publicly in the temple (John 2:14–15).",
        ),
        g(
            2,
            5,
            "How does John 2 prepare the reader for recurring conflict over Jesus' identity in later chapters?",
            "Questions of authority, temple, and signs surface early and deepen",
            "Conflict disappears after ch. 2",
            "The chapter is isolated",
            "Only Romans conflict with Jesus",
            "The Jews ask for a sign; tension over the temple begins (John 2:18–20).",
        ),
        g(
            2,
            5,
            "What christological implication arises from Jesus knowing what was in man?",
            "Divine omniscience — Jesus searches hearts",
            "Jesus was guessing",
            "Only angels know hearts",
            "Knowledge is impossible",
            "He needed no one to bear witness about man, for he himself knew (John 2:25).",
        ),
        # Ch3 +17
        g(
            3,
            3,
            "What does it mean that Nicodemus addressed Jesus as \"Rabbi\" and knew he was a teacher come from God?",
            "He recognized Jesus' authority but had not yet grasped spiritual rebirth",
            "He fully understood the Trinity",
            "He denied Jesus was a teacher",
            "He was mocking Jesus",
            "Nicodemus begins with partial recognition (John 3:2).",
        ),
        g(
            3,
            3,
            "How does the wind imagery in John 3:8 describe the Spirit's work?",
            "The Spirit moves mysteriously like wind — you hear it but cannot control its origin",
            "Wind proves there is no Spirit",
            "The Spirit is only weather",
            "Wind is evil",
            "So it is with everyone born of the Spirit (John 3:8).",
        ),
        g(
            3,
            3,
            "What does John 3:19–21 teach about why people reject the light?",
            "They love darkness because their deeds are evil — moral responsibility",
            "God forces them to hate light",
            "Light is too bright physically",
            "Everyone loves light automatically",
            "People hate the light lest their works be exposed (John 3:20).",
        ),
        g(
            3,
            3,
            "What role does John the Baptist play in John 3:22–30 after Nicodemus?",
            "He models pointing away from himself to Jesus — \"He must increase, I must decrease\"",
            "He competes with Jesus for crowds",
            "He denies Jesus",
            "He leaves the narrative forever",
            "The Baptist rejoices as the bridegroom's friend (John 3:29).",
        ),
        g(
            3,
            3,
            "What does \"born of water and Spirit\" (John 3:5) likely emphasize together?",
            "Cleansing and new life from God — not mere physical birth or ritual alone",
            "Only physical birth",
            "Water cancels Spirit",
            "Spirit cancels water",
            "Jesus speaks of entry into God's kingdom by God's initiative.",
        ),
        g(
            3,
            4,
            "How does John 3:13 support Jesus' unique authority to speak of heavenly things?",
            "Only the Son of Man descended from heaven; thus he alone reveals heaven",
            "Moses ascended higher than Jesus",
            "Angels taught Nicodemus",
            "No one needs heavenly revelation",
            "No one has ascended into heaven except he who descended (John 3:13).",
        ),
        g(
            3,
            4,
            "What is the relationship between belief and eternal life in John 3:15–16?",
            "Believing in the Son is the God-given means to eternal life",
            "Works earn life without faith",
            "Eternal life is unrelated to the Son",
            "Belief is optional",
            "Whoever believes in him should have eternal life (John 3:15–16).",
        ),
        g(
            3,
            4,
            "How does the bronze serpent typology (John 3:14–15) avoid suggesting salvation by works?",
            "Looking in faith to the lifted-up Son is parallel to Israel looking at the serpent — faith, not merit",
            "The serpent means works salvation",
            "Moses saved by magic",
            "The cross is optional",
            "As Moses lifted up the serpent, so must the Son of Man be lifted up (John 3:14).",
        ),
        g(
            3,
            4,
            "What does \"condemn\" mean in John 3:17–18 if Jesus came not to condemn the world?",
            "The world is already under judgment; belief or unbelief determines one's relation to that reality",
            "Jesus never speaks of judgment",
            "The world needs no Savior",
            "Condemnation is arbitrary",
            "Whoever does not believe is condemned already (John 3:18).",
        ),
        g(
            3,
            4,
            "How does John 3:31–36 climax the chapter's testimony theme?",
            "The one from heaven is above all; to reject the Son rejects the Father's word",
            "John the Baptist is above Jesus",
            "Testimony does not matter",
            "Heaven is irrelevant",
            "He who comes from heaven is above all (John 3:31).",
        ),
        g(
            3,
            5,
            "What nuance of krisis (judgment) in John 3:19 as \"this is the judgment\" should interpreters weigh?",
            "Judgment is exposed in the moral response to light — self-judgment by love of darkness",
            "Judgment is only future",
            "There is no present moral dimension",
            "Light has no ethical demand",
            "The light has come, and people loved darkness (John 3:19).",
        ),
        g(
            3,
            5,
            "How does John's use of \"eternal life\" in chapter 3 differ from mere endless existence?",
            "It is life in relationship with God through the Son — quality and communion, not only duration",
            "It means only living a long time",
            "It is the same as Hades",
            "John never defines life",
            "Eternal life is knowing the only true God and Jesus Christ (cf. John 17:3).",
        ),
        g(
            3,
            5,
            "What trinitarian hints appear in the Nicodemus discourse regarding Spirit, Son, and Father?",
            "The Spirit gives new birth; the Son must be lifted up; the Father sends the Son out of love",
            "Only the Father appears",
            "The Spirit is absent",
            "Trinity is denied",
            "Father, Son, and Spirit cooperate in salvation (John 3:5–17).",
        ),
        g(
            3,
            5,
            "How does the Baptist's \"from above\" vs. \"of the earth\" contrast (John 3:31) structure Johannine Christology?",
            "Jesus' origin determines his authority; earthly speakers are limited",
            "Jesus is only earthly",
            "Origin does not matter",
            "John the Baptist is from heaven",
            "He who is of the earth is earthly (John 3:31).",
        ),
        g(
            3,
            5,
            "What ethical implication follows from receiving the Father's testimony about the Son (John 3:33–36)?",
            "Disobeying the Son rejects God's own witness and forfeits life",
            "Ethics are unrelated",
            "Testimony is optional",
            "Obedience saves without faith",
            "Whoever does not obey the Son shall not see life (John 3:36).",
        ),
        g(
            2,
            4,
            "How does the master of the feast not knowing where the wine came from function in the Cana story?",
            "It contrasts human ignorance with the servants' knowledge — disciples see the source of the sign",
            "It proves the master was dishonest",
            "It means the miracle was fake",
            "It shows only Jesus drank the wine",
            "The servants who had drawn the water knew; the master did not (John 2:9).",
        ),
        g(
            2,
            5,
            "What does Jesus' cleansing of the temple foreshadow about his relationship to sacred space?",
            "His authority over true worship — the temple points to his body and messianic presence",
            "He rejected the temple forever",
            "He only wanted more money",
            "He was angry at animals",
            "Jesus drives out commerce as claim to divine authority over God's house (John 2:14–17).",
        ),
        g(
            2,
            5,
            "How does John 2:11 connect belief and signs?",
            "The disciples believed because the sign manifested Jesus' glory — faith tied to revelation",
            "Signs replace faith",
            "Belief is unrelated to signs",
            "Only crowds believe",
            "His disciples believed in him (John 2:11).",
        ),
        g(
            3,
            4,
            "How does John 3:5–8 combine water, Spirit, and wind imagery?",
            "They stress new birth from above — invisible yet real, like wind you cannot control",
            "They contradict each other",
            "Water cancels Spirit",
            "Wind replaces Spirit",
            "The Spirit blows where it wishes — like wind (John 3:8).",
        ),
        g(
            3,
            5,
            "What does John 3:35–36 add about the relationship between the Father and the Son?",
            "The Father has given all things into the Son's hand — supreme authority",
            "The Son has no authority",
            "The Father and Son disagree",
            "Authority belongs to Moses",
            "The Father loves the Son and has given all things into his hand (John 3:35).",
        ),
    ]
