"""John chapters 15–21 — 50 questions each."""
from __future__ import annotations

from john_quiz_spec_utils import zip_chapter

# fmt: off
_CH15: list[tuple[str, str, str, str, str, str]] = [
("What is Jesus called in John 15:1?", "The true vine", "The true door", "The true bread", "The true light", "I am the true vine (John 15:1)."),
("Who is the vinedresser?", "His Father", "A Roman soldier", "Moses", "Peter", "My Father is the vinedresser (John 15:1)."),
("What happens to every branch in Jesus that does not bear fruit?", "The Father takes it away", "It grows forever", "It becomes the trunk", "It is praised", "Every branch in me that does not bear fruit he takes away (John 15:2)."),
("What does the Father do to every branch that bears fruit?", "Prunes it, that it may bear more fruit", "Cuts it off immediately", "Leaves it wild", "Paints it", "Every branch that does bear fruit he prunes, that it may bear more fruit (John 15:2)."),
("What must disciples do to bear fruit?", "Abide in Jesus", "Travel widely", "Memorize only", "Avoid suffering", "Whoever abides in me and I in him, he it is that bears much fruit (John 15:5)."),
("What can disciples do apart from Jesus?", "Nothing", "Everything small", "Judge the world", "Heal alone", "Apart from me you can do nothing (John 15:5)."),
("What happens to branches that do not abide?", "They wither, are gathered, burned", "They flourish", "They become vines", "They are saved", "If anyone does not abide in me… thrown into the fire (John 15:6)."),
("What did Jesus say disciples were if they abided in him and his words?", "Clean because of the word spoken", "Unclean forever", "Self-cleaned", "Only ritually", "Already you are clean because of the word that I have spoken to you (John 15:3)."),
("What did Jesus command them to abide in?", "His love", "Roman law", "Temple money", "Fear", "Abide in my love (John 15:9)."),
("How did Jesus say they should keep his commandments?", "As he kept his Father's commandments", "Randomly", "Only if easy", "Never", "As I have kept my Father's commandments and abide in his love (John 15:10)."),
("What did Jesus say he spoke to them?", "These things that his joy might be in them and their joy full", "Only laws", "Only threats", "Only parables", "These things I have spoken to you, that my joy may be in you, and that your joy may be full (John 15:11)."),
("What is the greatest love?", "To lay down one's life for friends", "To give money", "To debate enemies", "To build synagogues", "Greater love has no one than this, that someone lay down his life for his friends (John 15:13)."),
("What did Jesus call disciples if they did what he commanded?", "Friends", "Servants only forever", "Strangers", "Judges", "You are my friends if you do what I command you (John 15:14)."),
("What did Jesus say he chose them for?", "That they should go and bear fruit", "That they should be rich", "That they should flee", "That they should hide", "You did not choose me, but I chose you… that you should go and bear fruit (John 15:16)."),
("What did Jesus say the world would do because it hated him?", "Hate them too", "Love them", "Ignore them", "Honor them", "If the world hates you, know that it has hated me before it hated you (John 15:18)."),
("Why would the world persecute them?", "Because they are not of the world", "Because they sin more", "Because they are Jews", "Because they are Greek", "If you were of the world, the world would love you as its own (John 15:19)."),
("What did Jesus say the servant is not greater than?", "His master", "His money", "His house", "His city", "A servant is not greater than his master (John 15:20)."),
("What did Jesus say they would do to disciples for his name's sake?", "Persecute them", "Crown them", "Ignore them", "Pay them", "They will persecute you (John 15:20)."),
("What would the Helper testify?", "About Jesus", "About Rome", "About Moses only", "About angels", "The Spirit of truth… will bear witness about me (John 15:26)."),
("What must disciples also do?", "Bear witness", "Stay silent", "Fight with swords", "Deny Jesus", "You also will bear witness (John 15:27)."),
("Theologically, what does vine imagery draw from?", "Isaiah 5 / Psalm 80 — Israel as vine; Jesus is true Israel", "Greek myths only", "No Old Testament", "Roman farming only", "I am the true vine (John 15:1)."),
("How does pruning relate to suffering?", "Discipline for fruitfulness — Father's care", "Punishment without hope", "Pain is meaningless", "Only wicked pruned", "He prunes… that it may bear more fruit (John 15:2)."),
("What does fruit mean in context?", "Obedient life and mission — not only converts", "Only grapes", "Wealth", "Buildings", "Bear fruit… so prove to be my disciples (John 15:8)."),
("How does friendship with Christ differ from servanthood?", "Friends know the Master's plans — revelation", "No difference", "Friends need no obedience", "Servants know more", "I have called you friends, for all that I have heard from my Father I have made known to you (John 15:15)."),
("What cosmic conflict underlies world hatred?", "Light vs darkness — disciples identified with Jesus", "Only political", "No conflict", "Only economic", "If they persecuted me, they will also persecute you (John 15:20)."),
("What does \"without me you can do nothing\" contribute to grace theology?", "Dependence on Christ for spiritual fruit — not self-sufficiency", "Works salvation", "Human autonomy", "Monastic isolation", "Apart from me you can do nothing (John 15:5)."),
("How does Spirit and church witness relate?", "Spirit empowers apostolic witness to Jesus", "Spirit replaces church", "Witness is only past", "Only book", "You will bear witness (John 15:27)."),
("What does chosenness in 15:16 guard against?", "Pride — election is for fruit and prayer answered", "Boasting in self", "Universalism only", "No mission", "You did not choose me, but I chose you (John 15:16)."),
("How does abiding prayer \"whatever you ask\" fit Johannine themes?", "Prayer in Jesus' name abiding in him", "Magic formula", "Health wealth only", "No conditions", "I chose you… whatever you ask the Father in my name, he may give it to you (John 15:16)."),
("What does world's guilt in hating Jesus mean?", "Rejecting Jesus rejects Father who sent him — no excuse", "World is innocent", "Hate is virtue", "Only Jews guilty", "They hated me without a cause (John 15:25)."),
("Scholarly link: Psalm 35 / 69 quotation?", "Righteous sufferer motif applied to Jesus", "Random quote", "Misapplied", "Only Psalm 23", "The word that is written in their Law must be fulfilled (John 15:25)."),
("How does joy theme connect to cross coming?", "Joy in fellowship before tribulation — Spirit joy", "Joy denied", "Only after resurrection in John", "No joy in Upper Room", "That my joy may be in you (John 15:11)."),
("What does \"clean\" word link to?", "Already pruned by word — preparation for fruit", "Physical bath", "Only circumcision", "Only priests", "You are already clean because of the word (John 15:3)."),
("How does mutual abiding work?", "Jesus in disciple, disciple in Jesus — mystical union language", "One-way only", "Only metaphor with no reality", "Only later mystics", "Abide in me, and I in you (John 15:4)."),
("What ethical fruit proves discipleship?", "Love and obedience — fruit visible", "Miracles only", "Wealth", "Titles", "By this my Father is glorified, that you bear much fruit and so prove to be my disciples (John 15:8)."),
("How does world hatred prepare for persecution in Acts?", "Early church faces same hostility Jesus predicted", "Acts denies persecution", "Only success", "No connection", "They will put you out of the synagogues (John 16:2)."),
("What does two witnesses (Spirit and disciples) evoke?", "Legal requirement — credible testimony", "Only Revelation 11", "Contradiction", "Only angels", "You will bear witness (John 15:27)."),
("How does \"I am the vine\" continue \"I am\" sayings?", "Seventh major image — covenant life source", "Breaks pattern", "Only metaphor", "No theology", "I am the true vine (John 15:1)."),
("What pastoral use for fruitless seasons?", "Abide — wait on pruning, not despair", "Cut off immediately", "Works harder alone", "Deny election", "Every branch… that does bear fruit he prunes (John 15:2)."),
("How does love commandment from 13 recur?", "Love each other — abiding enables love", "New topic", "Love canceled", "Only insiders", "This is my commandment, that you love one another (John 15:12)."),
("What does slave vs friend knowledge mean for revelation?", "Progressive disclosure — friends know Master's business", "Slaves know more", "Knowledge is sin", "Only apostles are friends", "I have called you friends… I have made known to you (John 15:15)."),
("How does hatred \"without a cause\" defend Jesus' innocence?", "Fulfills Scripture — righteous sufferer", "Jesus deserved hate", "No prophecy", "Cause is money", "They hated me without a cause (John 15:25)."),
("What missional thrust in chosen and sent?", "Church sent as Jesus was sent", "Stay in Upper Room", "Only Jews sent", "Sending is metaphor", "As the Father has sent me, even so I am sending you (John 20:21 cf. mission)."),
("How does branch in fire warn?", "Final judgment for unfruitful profession", "Universalism", "Fire is only metaphor with no end", "Works save", "Thrown into the fire (John 15:6)."),
("What trinitarian note in Father glorified by fruit?", "God's glory in disciples' fruitfulness — Spirit's work", "Father needs ego", "Glory is human only", "No Spirit", "My Father is glorified (John 15:8)."),
("How does 15:22 relate to guilt?", "Jesus' word and works remove excuse — greater accountability", "Removes guilt", "Ignorance saves", "No judgment", "If I had not come and spoken to them, they would not have been guilty of sin (John 15:22)."),
("What does \"they have seen and hated\" add?", "Rejection despite revelation — culpable unbelief", "They never saw", "Hate is innocent", "Seeing saves automatically", "They have seen and hated both me and my Father (John 15:24)."),
("What comforter promise bridges to 16?", "Spirit will come when Jesus goes — next chapter details", "Spirit canceled", "Jesus stays", "No bridge", "When the Helper comes, whom I will send to you from the Father (John 15:26)."),
("What did Jesus say would happen if he had not come and spoken to them?", "They would not be guilty of sin — now they have no excuse", "They would be guiltier without him", "Sin would not exist", "They would be innocent", "If I had not come and spoken to them, they would not have been guilty of sin (John 15:22)."),
("What did Jesus say they hated without a cause?", "Himself", "Moses", "The temple", "The Sabbath", "They hated me without a cause (John 15:25)."),
]

_CH16: list[tuple[str, str, str, str, str, str]] = [
("What did Jesus say would make disciples sorrowful?", "His going away", "His miracles stopping", "Their poverty", "Roman taxes", "Because I have said these things to you, sorrow has filled your heart (John 16:6)."),
("What did Jesus say their sorrow would turn into?", "Joy", "Wealth", "Fame", "Revenge", "Your sorrow will turn into joy (John 16:20)."),
("What illustration did Jesus use about childbirth?", "A woman has pain then joy when child is born", "A farmer's field", "A king's war", "A ship's sail", "When a woman is giving birth… but when she has delivered the baby… joy (John 16:21)."),
("What did Jesus say disciples would ask in his name on that day?", "Nothing — Father loves them because they loved Jesus", "For gold", "For revenge", "For thrones", "In that day you will ask nothing of me… the Father himself loves you (John 16:26–27)."),
("What did Jesus say the Helper would do to the world?", "Convict concerning sin, righteousness, and judgment", "Flatter the world", "Ignore sin", "Build cities", "He will convict the world concerning sin and righteousness and judgment (John 16:8)."),
("Concerning sin, why would the Spirit convict?", "Because they do not believe in Jesus", "Because they eat meat", "Because they are poor", "Because they are Gentiles", "Concerning sin, because they do not believe in me (John 16:9)."),
("Concerning righteousness, because Jesus went where?", "To the Father", "To Rome", "To Egypt", "To the temple only", "Concerning righteousness, because I go to the Father, and you will see me no longer (John 16:10)."),
("Concerning judgment, because what ruler was judged?", "The ruler of this world", "Pilate", "Herod", "Caesar", "Concerning judgment, because the ruler of this world is judged (John 16:11)."),
("What did Jesus say the Spirit would do for disciples?", "Guide into all truth", "Write new Scripture alone", "Ignore Old Testament", "Give wealth", "When the Spirit of truth comes, he will guide you into all the truth (John 16:13)."),
("What would the Spirit declare?", "Things to come", "Roman politics", "Gossip", "Nothing", "He will declare to you the things that are to come (John 16:13)."),
("What did Jesus say would scatter disciples?", "Each to his own home", "Angels", "Soldiers only", "Fish", "You will leave me alone… you will be scattered, each to his own (John 16:32)."),
("Who did Jesus say would be with him?", "The Father", "Judas", "Pilate", "No one", "Yet I am not alone, for the Father is with me (John 16:32)."),
("What did Jesus say disciples would have in him?", "Peace", "Swords", "Fear", "Confusion", "I have said these things to you, that in me you may have peace (John 16:33)."),
("What did Jesus say they would have in the world?", "Tribulation", "Only health", "Only honor", "Only rest", "In the world you will have tribulation (John 16:33)."),
("What did Jesus say to take heart for?", "He has overcome the world", "Money", "Rome's fall", "Their strength", "Take heart; I have overcome the world (John 16:33)."),
("What did Jesus say about speaking figuratively?", "A time coming when he would tell plainly about the Father", "Never plain speech", "Only parables forever", "Only to angels", "The hour is coming when I will no longer speak to you in figures of speech (John 16:25)."),
("What did disciples say made Jesus' speech clearer?", "Figures — then plain speech promise", "Nothing", "Angels helped", "Only Greek", "Ah, now you are speaking plainly and not using figurative speech (John 16:29)."),
("What did Jesus say about their scattering?", "They would leave him alone — yet Father with him", "They would never return", "They would all die", "They would betray openly", "You will leave me alone (John 16:32)."),
("What hour was coming when disciples would not see Jesus?", "Brief time — then see him again", "Forever gone", "Only after millennium", "Never see", "A little while, and you will see me no longer; and again a little while, and you will see me (John 16:16)."),
("What question did disciples ask each other about \"little while\"?", "What he meant by a little while", "Where is bread", "Who will betray", "When is Passover", "What does he mean by a little while? (John 16:18)."),
("Theologically, what is Spirit's convicting work?", "Exposing sin, Christ's righteousness, Satan's defeat — prevenient grace", "Only punishment", "Only comfort", "World ignores", "He will convict the world (John 16:8)."),
("How does sorrow-to-joy apply to resurrection?", "Grief at cross becomes joy at seeing risen Lord", "Joy never comes", "Only metaphor", "Only for Mary", "Your sorrow will turn into joy (John 16:20)."),
("What does \"ask nothing of me\" in 16:26 mean?", "Debated — direct access to Father in Jesus' name — new covenant prayer", "No prayer ever", "Only Jesus prays", "Angels mediate", "You will ask me nothing (John 16:23)."),
("How does Spirit guide into truth relate to later writings?", "Apostolic doctrine under Spirit inspiration — Scripture", "Contradicts Scripture", "Only oral", "Spirit contradicts Jesus", "Guide you into all the truth (John 16:13)."),
("What does overcoming the world mean?", "Victory through cross — faith conquers world system", "Military conquest", "Wealth", "Escape body", "I have overcome the world (John 16:33)."),
("How does tribulation promise help persecuted church?", "Realistic expectation — Christ's peace amid trouble", "Prosperity gospel", "No suffering", "Tribulation is failure", "In the world you will have tribulation (John 16:33)."),
("What does Father loving disciples directly show?", "Intimacy in new covenant — not only through rabbi", "Father hates disciples", "Only Son loved", "Love is generic", "The Father himself loves you (John 16:27)."),
("How does \"figures of speech\" vs plain point to Johannine communication?", "Progressive understanding — post-resurrection clarity", "Jesus is unclear forever", "Only insiders get plain", "Parables only", "I will no longer speak… in figures (John 16:25)."),
("What does scattered disciples fulfill?", "Sheep scattered — Zechariah 13:7 echo", "Nothing", "Victory", "Unity only", "Strike the shepherd, and the sheep will be scattered (Matt 26:31 / John context)."),
("Scholarly debate: 16:25-30 and realized eschatology?", "Debates on when \"plain\" speech arrives — resurrection community", "All agree", "No debate", "John denies future", "You will ask me nothing (John 16:23)."),
("How does Spirit glorify Jesus?", "Takes what is Jesus' and declares — trinitarian mission", "Glorifies self", "Ignores Jesus", "Only Father glory", "He will glorify me, for he will take what is mine and declare it to you (John 16:14)."),
("What does things to come include?", "Pentecost onward — church age revelation", "Only AD 70", "Nothing", "Only end times map", "He will declare… things that are to come (John 16:13)."),
("How does peace differ from world's?", "Christ's peace — reconciliation with God", "Same as Rome's Pax", "Absence of thought", "Only inner", "My peace I give to you (John 16:33)."),
("What courage from \"I have overcome\"?", "Satan, world, death defeated in Christ — believers share victory", "Overcome means rich", "Only future", "No devil", "Take heart; I have overcome the world (John 16:33)."),
("How does 16:2 synagogue exclusion prepare?", "Community cost — apostolic experience", "Never happens", "Only metaphor", "Synagogue loves Christians", "Whoever kills you will think he is offering service to God (John 16:2)."),
("What does not believing Jesus as sin mean?", "Supreme sin — rejection of revelation", "Small sin", "Sin is only actions", "Belief optional", "Concerning sin, because they do not believe in me (John 16:9)."),
("How is ruler of world judged?", "Cross — defeat of Satan's claim", "No defeat", "Only in Revelation", "Rome judged", "The ruler of this world is judged (John 16:11)."),
("What does little while sorrow/joy teach about eschatology?", "Already/not yet — resurrection joy in seed form", "Only future millennium", "No future", "Joy is only metaphor", "Your sorrow will turn into joy (John 16:20)."),
("How does Spirit take from Christ and declare?", "Trinitarian procession — revelation chain", "Spirit independent", "Christ hides truth", "Only human preaching", "He will take what is mine and declare it to you (John 16:14)."),
("What pastoral word for confused disciples?", "Jesus knows their questions — Spirit will teach", "Leave them confused", "Silence is best", "Only scholars", "Do you now believe? (John 16:31)."),
("How does 16:33 climax Farewell Discourse?", "Peace and victory summary before Gethsemane", "Discourse fails", "No climax", "Only fear", "In me you may have peace (John 16:33)."),
("What link between prayer in 16:23-24 and fruit in 15?", "Ask in Jesus' name — fruit and prayer connected", "No connection", "Prayer replaces fruit", "Only apostles", "Whatever you ask the Father in my name, he may give it to you (John 16:23)."),
("How does \"you have overcome me\" misread avoided?", "Jesus overcomes world — not disciples alone", "Disciples alone win", "World wins", "No overcoming", "I have overcome the world (John 16:33)."),
("What does believing after plain speech (16:29-30) show?", "Still dependent on Jesus — not full understanding", "Perfect knowledge", "No faith needed", "Angels taught", "Now we know that you know all things (John 16:30)."),
("How does scattered alone theme prepare for cross?", "Desertion — yet Father with Son", "Disciples stay", "No loneliness", "Judas only leaves", "You will leave me alone (John 16:32)."),
("What pneumatology: Spirit proceeds from Father?", "Sent in Son's name — mission trinity", "Only from Son", "Only created", "Spirit is not personal", "I will send him to you from the Father (John 16:28)."),
("How does joy no one take complete resurrection joy?", "Eschatological security — gift of Christ", "Joy can be stolen", "Only earthly", "Joy is mood only", "Your joy no one will take from you (John 16:22)."),
("What ethical warning in 16:1?", "Jesus spoke to keep them from stumbling — persecution shock", "No stumbling possible", "Stumbling is good", "Only for Jews", "I have said all these things to you to keep you from falling away (John 16:1)."),
("What did Jesus say the Spirit would not speak on his own authority?", "Whatever he hears — he will speak of what is to come", "His own inventions", "Roman law", "Nothing", "He will not speak on his own authority, but whatever he hears he will speak (John 16:13)."),
("What did Jesus say would make disciples sorrowful about his going?", "They would not see him — then see him again", "They would lose money", "They would miss miracles only", "They would hate the Father", "A little while, and you will not see me, and again a little while, and you will see me (John 16:16)."),
]

_CH17: list[tuple[str, str, str, str, str, str]] = [
("What hour had come?", "For the Son of Man to be glorified", "For Passover only", "For Rome to fall", "For temple cleansing", "Father, the hour has come; glorify your Son (John 17:1)."),
("What did Jesus ask the Father to give him?", "Glory — that the Son may glorify the Father", "Silver", "A throne in Rome", "More disciples only", "Glorify your Son that the Son may glorify you (John 17:1)."),
("What did Jesus say he had manifested?", "The Father's name to the people given him", "His own private religion", "Roman law", "Temple blueprints", "I have manifested your name to the people whom you gave me out of the world (John 17:6)."),
("What did Jesus say was eternal life?", "Knowing the only true God and Jesus Christ whom he sent", "Living forever only biologically", "Keeping law perfectly", "Being Jewish", "This is eternal life, that they know you, the only true God, and Jesus Christ whom you have sent (John 17:3)."),
("What did Jesus say he had finished?", "The work given him to do", "Building the temple", "Defeating Rome", "Writing Scripture", "I glorified you on earth, having accomplished the work that you gave me to do (John 17:4)."),
("For whom did Jesus pray?", "Those the Father gave him — not for the world in same way", "Only Pharisees", "Only Romans", "Only angels", "I am praying for them. I am not praying for the world but for those whom you have given me (John 17:9)."),
("What did Jesus ask — that they may be one?", "As Father and Son are one", "As soldiers are one", "As strangers are one", "As competitors are one", "That they may all be one, just as you, Father, are in me, and I in you (John 17:21)."),
("What did Jesus say he gave them?", "The words the Father gave him", "Wealth", "Weapons", "A kingdom on earth", "I have given them your word (John 17:14)."),
("What did Jesus say the world hated them because of?", "Not belonging to the world", "Their poverty", "Their race", "Their boats", "I have given them your word, and the world has hated them because they are not of the world (John 17:14)."),
("What did Jesus not ask the Father to take them out of?", "The world", "Temptation", "Suffering", "Trials", "I do not ask that you take them out of the world (John 17:15)."),
("What did Jesus ask the Father to keep them from?", "The evil one", "Work", "Marriage", "Scripture", "Keep them from the evil one (John 17:15)."),
("What did Jesus say he sanctified himself for?", "That they also may be sanctified in truth", "That they may be rich", "That Rome may fall", "That priests may rule", "And for their sake I consecrate myself, that they also may be sanctified in truth (John 17:19)."),
("What did Jesus desire for those who believe through their word?", "That the world may believe", "That Rome converts", "That war ends", "That temple rebuilds", "That the world may believe that you have sent me (John 17:21)."),
("What glory did Jesus ask to see?", "The glory he had with the Father before the world existed", "Earthly fame", "Military medals", "Temple gold", "Father, I desire that they also… may be with me where I am, to see my glory that you have given me because you loved me before the foundation of the world (John 17:24)."),
("What did Jesus make known?", "The Father's name — and will continue", "Secrets of Rome", "Future stock markets", "Angel names", "I made known to them your name, and I will continue to make it known (John 17:26)."),
("Theologically, what is high priestly prayer?", "Intercession before cross — covenant solidarity", "Only poetry", "No effect", "Only for angels", "Father… (John 17:1)."),
("How does unity theme function ecumenically?", "Trinitarian pattern for church unity — not mere organization", "Uniformity only", "Unity impossible", "Only invisible", "That they may be one as we are one (John 17:22)."),
("What does \"knowing\" God in eternal life mean?", "Covenant relationship — not mere facts", "Academic trivia", "Visions only", "Works only", "That they know you, the only true God (John 17:3)."),
("How does not taking out of world relate to mission?", "In but not of — salt and light in culture", "Monastic escape", "Worldly conformity", "Only desert monks", "Not… take them out of the world (John 17:15)."),
("What does protection from evil one promise?", "Spiritual warfare — guarded in mission", "No suffering", "Health guarantee", "Wealth", "Keep them from the evil one (John 17:15)."),
("How does glory before world foundation show pre-existence?", "Christ shared Father's glory — eternal Son", "Jesus began at Bethlehem only", "Glory is only human", "No Trinity", "You loved me before the foundation of the world (John 17:24)."),
("What does sanctify in truth mean?", "Set apart by God's word — holiness", "Physical washing only", "Only priests", "Truth is optional", "Sanctify them in the truth; your word is truth (John 17:17)."),
("How does prayer for future believers include us?", "Those who believe through apostolic word — church age", "Only twelve apostles", "Only first century", "Excludes moderns", "I do not ask for these only, but also for those who will believe in me through their word (John 17:20)."),
("What does mutual indwelling of believers in God show?", "Participation in divine life — profound union", "Pantheism", "Only metaphor", "Only apostles", "That they may all be one… I in them and you in me (John 17:23)."),
("How does world believe through church's unity?", "Apologetic — love and oneness witness", "Force conversion", "Unity irrelevant", "Only miracles convert", "That the world may believe (John 17:21)."),
("What does Jesus' report card \"I glorified you\" mean?", "Obedient incarnate life — mission accomplished", "Boasting", "Incomplete life", "Only future glory", "I glorified you on earth (John 17:4)."),
("Scholarly debate: John 17 and second temple prayer patterns?", "Similarities to synagogue prayers — Jewish roots of Christian prayer", "No Jewish roots", "Copied from Mithras", "No debate", "Scholars note Jewish prayer forms."),
("How does \"name\" revelation work?", "Father's character revealed in Son — covenant name", "Secret password", "Only title \"God\"", "Name is magic", "I have manifested your name (John 17:6)."),
("What does love with which Father loved Son before world imply?", "Eternal generation — love within Trinity", "Love begins at Bethlehem", "Only human affection", "Father did not love Son", "You loved me before the foundation of the world (John 17:24)."),
("How does 17:18 sending parallel Jesus' mission?", "As Father sent Son, Son sends disciples", "Disciples send Jesus", "No mission", "Only angels sent", "As you sent me into the world, so I have sent them into the world (John 17:18)."),
("What does joy fulfilled in themselves (17:13) mean?", "Sharing Jesus' own joy — eschatological gift", "Temporary emotion", "Only laughter", "Wealth joy", "That they may have my joy fulfilled in themselves (John 17:13)."),
("How does oneness protect from discord?", "Trinitarian love model — not authoritarian clone", "Forced agreement", "Diversity denied", "Only invisible unity", "That they may become perfectly one (John 17:23)."),
("What does world knowing Father sent Jesus depend on?", "Unity of disciples — missional apologetic", "Military power", "Wealth", "Temple rituals", "That the world may know that you sent me (John 17:23)."),
("How does Jesus' prayer end on note of love?", "Father's love in Christ indwelling believers — mutual love", "Ends cold", "Love denied", "Only fear", "That the love with which you have loved me may be in them, and I in them (John 17:26)."),
("What does kept in Father's name mean?", "Security — divine preservation", "Name as charm", "Only human guards", "Salvation by label only", "While I was with them, I kept them in your name (John 17:12)."),
("How does none lost except son of destruction read?", "Judas' apostasy — Scripture fulfillment", "God lost sheep randomly", "No election", "Judas innocent", "None of them is lost but the son of destruction (John 17:12)."),
("What does glory given to disciples (17:22) mean?", "Sharing in Christ's glory — adoption honor", "Physical light only", "Wealth transfer", "Angels' glory stolen", "The glory that you have given me I have given to them (John 17:22)."),
("How does prayer shape Johannine ecclesiology?", "Church as loved, sent, unified, protected community", "Church invisible only", "Church is nation", "No community", "Holy Father, keep them in your name (John 17:11)."),
("What does truth as sanctifier contrast?", "Pilate's \"what is truth\" — Jesus' word sanctifies", "Truth unknowable", "Relativism", "Only philosophy", "Your word is truth (John 17:17)."),
("How does 17:5 glorification request fit narrative?", "Looks to cross as glorification — hour come", "Glory without cross", "Only resurrection", "Only ascension", "Glorify me… with the glory that I had with you before the world existed (John 17:5)."),
("What pastoral comfort in kept from evil?", "Assurance amid persecution — not removal from world", "No evil exists", "Christians never suffer", "Health promise", "Keep them from the evil one (John 17:15)."),
("How does mutual seeing glory fulfill hope?", "Beatific vision theme — future with Christ", "No heaven", "Only metaphor", "Only apostles see", "That they may see my glory (John 17:24)."),
("What does \"I in them\" contribute to union with Christ?", "Mystical union — ethical transformation", "Physical fusion", "Only legal", "Only future", "I in them and you in me (John 17:23)."),
("How does Jesus' prayer before cross model Christian prayer?", "Trinitarian, scriptural, missional — Jesus prays as he taught", "Prayer useless", "Only spontaneous", "No Father address", "Father… (John 17:1)."),
("What missional edge in world believing?", "Eschatological hope — gospel success", "Universalism automatic", "World never believes", "Only Israel", "That the world may believe (John 17:21)."),
("How does 17:26 love abiding close Gospel's love theme?", "Love commandment fulfilled in divine indwelling", "Love ends", "Only human love", "Law without love", "That the love… may be in them (John 17:26)."),
("What did Jesus pray the Father would give believers in Jesus' glory?", "The same glory — that they may be one", "Wealth", "A throne in Rome", "Nothing", "The glory that you have given me I have given to them (John 17:22)."),
("What did Jesus say he had given to the Father?", "Glory on earth", "Only money", "Only criticism", "Silent obedience", "I glorified you on earth, having accomplished the work that you gave me to do (John 17:4)."),
("What did Jesus say he had given to those the Father gave him?", "The words the Father gave him", "His own private opinions", "Roman citizenship", "A sword", "I have given them your word (John 17:14)."),
("What did Jesus pray the Father would give them that they may be one?", "Glory", "Riches", "Freedom from Rome", "Long life", "The glory that you have given me I have given to them (John 17:22)."),
]

_CH18: list[tuple[str, str, str, str, str, str]] = [
("Where did Jesus go across the Kidron?", "A garden", "The temple", "The sea", "Caesarea", "Jesus went out… across the brook Kidron, where there was a garden (John 18:1)."),
("Whom did Jesus meet in the garden?", "Judas with soldiers", "Only disciples", "Only angels", "Pilate", "Judas, who betrayed him, knew the place… Jesus met them (John 18:2–5)."),
("What did Jesus say when they said they sought Jesus?", "I am he", "Run away", "I am not he", "Ask Pilate", "Jesus said to them, \"I am he\" (John 18:5)."),
("What happened when Jesus said \"I am\"?", "They drew back and fell to the ground", "They rejoiced", "They healed", "They left", "When he said to them, \"I am he,\" they drew back and fell to the ground (John 18:6)."),
("What did Peter do to the high priest's servant?", "Cut off his right ear", "Healed him first", "Kissed him", "Paid him", "Simon Peter… struck the high priest's servant and cut off his right ear (John 18:10)."),
("What was the servant's name?", "Malchus", "Caesar", "Herod", "Annas", "The servant's name was Malchus (John 18:10)."),
("What did Jesus tell Peter about the cup?", "Shall I not drink the cup the Father has given me?", "Fight harder", "Run", "Hide", "Put your sword into its sheath; shall I not drink the cup…? (John 18:11)."),
("Whom did they lead Jesus to first?", "Annas", "Pilate directly", "Herod only", "Caiaphas only", "First they led him to Annas (John 18:13)."),
("Who was high priest that year?", "Caiaphas", "Annas", "Herod", "Pilate", "Caiaphas was the high priest that year (John 18:13)."),
("Who followed Jesus into the courtyard?", "Peter and another disciple", "All twelve", "No one", "Judas only", "Simon Peter was following Jesus, and so was another disciple (John 15:15–16)."),
("What did the servant girl ask Peter?", "You also are not one of this man's disciples, are you?", "Will you buy bread?", "Who is your king?", "Where is Jesus?", "You also are not one of this man's disciples, are you? (John 18:17)."),
("How many times did Peter deny before the rooster crowed?", "Three times", "Once", "Seven times", "Never", "Again Peter denied it, and at once a rooster crowed (John 18:27)."),
("What did Pilate ask Jesus?", "Are you the King of the Jews?", "Are you a priest?", "Are you from Egypt?", "Are you a fisherman?", "Are you the King of the Jews? (John 18:33)."),
("What did Jesus say his kingdom was not?", "Of this world", "Of David", "Of heaven", "Of angels", "My kingdom is not of this world (John 18:36)."),
("What did Jesus say his servants would do if his kingdom were of this world?", "Fight", "Pay taxes", "Flee", "Hide", "If my kingdom were of this world, my servants would have been fighting (John 18:36)."),
("What did Pilate say about truth?", "What is truth?", "Truth is clear", "I love truth", "Truth is money", "What is truth? (John 18:38)."),
("Whom did the crowd ask to release instead of Jesus?", "Barabbas", "Pilate", "Herod", "Peter", "Release for you the King of the Jews… Barabbas (John 18:39–40)."),
("What was Barabbas?", "A robber", "A priest", "A scribe", "A fisherman", "Now Barabbas was a robber (John 18:40)."),
("Theologically, what does garden evoke?", "Eden reversal — new Adam obedient to death", "Random park", "No theology", "Only agriculture", "Garden… Kidron (John 18:1)."),
("How does \"I am\" in arrest show power?", "Divine name — officers fall", "Jesus is weak", "Name is magic word", "No power", "They drew back and fell (John 18:6)."),
("What does sword rebuke teach?", "Violence not Messianic means — cup from Father", "Pacifism only", "War is good", "Peter is praised", "Put your sword into its sheath (John 18:11)."),
("How does Annas/Caiaphas sequence reflect history?", "Annas still power behind — Johannine detail", "Contradiction", "Only one high priest", "No history", "First to Annas (John 18:13)."),
("What does Peter's denial fulfill?", "Jesus' prediction — weakness and restoration theme", "Nothing", "Peter is devil", "No restoration", "You will deny me three times (John 13:38)."),
("How does kingdom not of world answer Pilate?", "Spiritual reign — not military coup", "Jesus wants Rome", "Kingdom is Rome", "Only future", "My kingdom is not from the world (John 18:36)."),
("What does Pilate's truth question show?", "Cynicism or despair — contrast Jesus as truth", "Perfect philosophy", "Faith", "Love of truth", "What is truth? (John 18:38)."),
("Why choose Barabbas?", "Crowd prefers insurrectionist — ironic choice", "Barabbas is innocent", "Random", "Pilate loves Barabbas", "Release… Barabbas (John 18:40)."),
("How does another disciple with Peter show?", "Beloved disciple access — eyewitness", "Legend", "Only Peter matters", "Two deny", "Another disciple… was known to the high priest (John 18:15)."),
("What does charcoal fire echo?", "John 21 restoration — same setting motif", "Random", "No chapter 21", "Only cold", "They were standing… warming themselves around a charcoal fire (John 18:18)."),
("Scholarly view: historicity of trial?", "Core events widely accepted; details harmonized across Gospels", "All fiction", "Only John true", "No study", "Scholars debate sequence."),
("How does Jesus witness to kingdom before Pilate?", "Testimony to gentile authority — universal scope", "Jesus silent always", "Only Jews matter", "Pilate converts", "You say that I am a king (John 18:37)."),
("What does born to bear witness to truth mean?", "Messiah witnesses to God's kingdom — Pilate's realm", "Only subjective truth", "No witness", "Only apostles", "For this purpose I was born… to bear witness to the truth (John 18:37)."),
("How does crowd's \"We have no king but Caesar\" betray?", "National apostasy — rejecting messianic hope", "Faithful statement", "Only sarcasm", "Caesar is Messiah", "We have no king but Caesar (John 19:15)."),
("What does binding Jesus show?", "Shepherd struck, sheep scattered — passion prophecy", "Orderly arrest", "Jesus fights", "No binding", "They bound him (John 18:12)."),
("How does Peter's warming by fire show cowardice?", "Proximity to trial while denying — dramatic irony", "Peter is brave", "Fire is irrelevant", "Only cold", "Peter was standing… warming himself (John 18:25)."),
("What does maid and others questioning Peter show?", "Escalating pressure — three denials", "One question only", "Peter silent", "Only one person", "They said to him… (John 18:25–27)."),
("How does rooster crow fulfill?", "Jesus' word precise — morning signal", "Random bird", "No prophecy", "Evening only", "The rooster crowed (John 18:27)."),
("What does lead to Annas first suggest about trial?", "Preliminary hearing — Jewish leadership intrigue", "Roman law", "Only Pilate", "No hearing", "Led him to Annas first (John 18:13)."),
("How does Jesus' answer to king question define mission?", "Kingdom is truth — Pilate faces claim", "Kingdom is army", "Jesus denies kingship", "Only spiritual later", "You say that I am a king (John 18:37)."),
("What apologetic value in Pilate finding no guilt?", "Innocence declared — yet condemned", "Pilate is right always", "No innocence", "Only Jewish guilt", "I find no guilt in him (John 18:38)."),
("How does world in Pilate scene contrast Jesus' kingdom?", "Rome's power vs. truth — clash of realms", "Same realm", "No clash", "Only spiritual", "Behold your King! (John 19:14)."),
("What does band of soldiers imply?", "Roman involvement — serious arrest", "Small group", "Only disciples", "Only Jews", "A band of soldiers and some officers from the chief priests (John 18:3)."),
("How does Judas know the place?", "Intimate disciple — betrayal of friendship", "He followed randomly", "Jesus hid", "No meetings", "Judas, who betrayed him, knew the place (John 18:2)."),
("What lantern/torch detail add?", "Night search — irony of light seeking Light", "Daytime", "No irony", "Only practical", "Judas… went there with lanterns and torches (John 18:3)."),
("What does Jesus protect disciples in arrest?", "Let these men go — shepherd cares for sheep", "Disciples arrested too", "No care", "Random", "If you seek me, let these men go (John 18:8)."),
("How does Malchus' ear healing in Synoptics relate?", "Jesus heals violence he condemned — mercy", "John contradicts", "No healing", "Peter praised", "Malchus' ear (cf. Luke 22:51)."),
("What does Peter follow at distance show?", "Brave yet failing — mixed courage", "Perfect courage", "No fear", "Never follows", "Simon Peter was following Jesus (John 18:15)."),
("What does release at Passover custom show?", "Irony — true Passover Lamb not released", "Custom is fiction", "Barabbas is lamb", "No irony", "Release one prisoner (John 18:39)."),
("What did the high priest ask Jesus about his disciples and teaching?", "Jesus answered openly — he spoke in synagogues and temple", "Jesus refused to answer", "Jesus denied disciples", "Jesus denied teaching", "I have spoken openly to the world… I always taught in synagogues and in the temple (John 18:20)."),
("What did one of the officers do when Jesus answered the high priest?", "Struck Jesus — is that how you answer?", "Praised Jesus", "Arrested Caiaphas", "Left", "One of the officers standing by struck Jesus… (John 18:22)."),
("What did Pilate ask Jesus — are you the King of the Jews?", "Jesus asked if Pilate spoke on his own or others told him", "Jesus denied kingship", "Jesus refused to speak", "Jesus called angels", "Do you say this of your own accord, or did others say it to you about me? (John 18:34)."),
]

_CH19: list[tuple[str, str, str, str, str, str]] = [
("What did Pilate have soldiers do to Jesus?", "Scourge him", "Crown him king in sincerity", "Release him", "Send him to Herod", "Pilate took Jesus and flogged him (John 19:1)."),
("What did soldiers weave for Jesus' head?", "A crown of thorns", "A gold crown", "A silk hat", "A laurel of olive", "They twisted together a crown of thorns and put it on his head (John 19:2)."),
("What color robe did they put on Jesus?", "Purple", "White", "Blue", "Red", "They arrayed him in a purple robe (John 19:2)."),
("What did Pilate say to the crowd?", "Behold your King!", "Crucify him now", "He is innocent", "Free him", "Behold your King! (John 19:14)."),
("What did the chief priests say?", "We have no king but Caesar", "We love Jesus", "We need a sign", "We follow Moses only", "We have no king but Caesar (John 19:15)."),
("Where was Jesus crucified?", "The Place of a Skull, called Golgotha in Hebrew", "Olivet", "Jericho", "Nazareth", "They took Jesus… to the place called The Place of a Skull, which in Aramaic is called Golgotha (John 19:17)."),
("Who carried Jesus' cross?", "Jesus went out bearing his own cross", "Simon of Cyrene only in John", "Peter", "Soldiers only", "He went out, bearing his own cross (John 19:17)."),
("What did Pilate write on the inscription?", "Jesus of Nazareth, the King of the Jews", "This is a robber", "King of Rome", "Innocent man", "Jesus of Nazareth, the King of the Jews (John 19:19)."),
("In how many languages was the inscription?", "Three — Hebrew, Latin, Greek", "One", "Two", "Four", "Written in Hebrew, in Latin, and in Greek (John 19:20)."),
("What did the soldiers do with Jesus' garments?", "Cast lots", "Burn them", "Return to Mary", "Sell them to priests", "They cast lots to see whose each should be (John 19:24)."),
("What Scripture did dividing garments fulfill?", "They divided my garments among them", "He was led like a lamb", "My God, my God", "I am the vine", "They divided my garments among them, and for my clothing they cast lots (John 19:24)."),
("Who stood by the cross?", "His mother, her sister, Mary Magdalene, Mary of Clopas", "Only soldiers", "Only Pharisees", "No one", "Standing by the cross of Jesus were his mother… (John 19:25)."),
("What did Jesus say to his mother?", "Woman, behold, your son!", "Why have you forsaken me?", "It is finished", "I thirst", "Woman, behold, your son! (John 19:26)."),
("To whom did Jesus entrust his mother?", "The beloved disciple", "Peter", "James", "Joseph", "Behold your mother! (John 19:27)."),
("What did Jesus say he thirsted for?", "To fulfill Scripture", "Only physical thirst", "Wine only", "Power", "I thirst (John 19:28)."),
("What did they put on hyssop to Jesus' mouth?", "Sour wine", "Water", "Oil", "Honey", "They put it on hyssop and brought it to his mouth (John 19:29)."),
("What did Jesus say when he had received the sour wine?", "It is finished", "Father, forgive", "Into your hands", "Why forsaken", "When Jesus had received the sour wine, he said, \"It is finished\" (John 19:30)."),
("What did a soldier pierce Jesus' side with?", "A spear", "A sword", "An arrow", "A nail", "One of the soldiers pierced his side with a spear (John 19:34)."),
("What came out of Jesus' side?", "Blood and water", "Only water", "Only blood", "Oil", "At once there came out blood and water (John 19:34)."),
("Who asked Pilate for Jesus' body?", "Joseph of Arimathea", "Nicodemus first in line", "Mary", "Peter", "Joseph of Arimathea… asked Pilate that he might take away the body of Jesus (John 19:38)."),
("How much spices did Nicodemus bring?", "About seventy-five pounds", "One pound", "Ten pounds", "A hundred denarii", "Nicodemus… brought a mixture of myrrh and aloes, about seventy-five pounds in weight (John 19:39)."),
("Theologically, what does crown of thorns signify?", "Curse of creation — thorns from Genesis 3 borne by second Adam", "Royal honor only", "No meaning", "Roman joke only", "Crown of thorns (John 19:2)."),
("How does inscription as King of Jews function ironically?", "True charge — crucified as king", "False title", "Only sarcasm with no truth", "Pilate believes", "The King of the Jews (John 19:19)."),
("What does lots for garments fulfill?", "Psalm 22 — righteous sufferer", "Random gambling", "No prophecy", "Psalm 23", "They divided my garments (John 19:24)."),
("How does woman behold son provide for Mary?", "Beloved disciple adopts Mary — new family", "Mary abandoned", "Only metaphor", "Jesus insults Mary", "Behold your son! (John 19:26)."),
("What does thirst fulfill?", "Scripture — details of passion planned", "Random discomfort", "No Scripture", "Only physical", "After this, Jesus, knowing that all was now finished, said (to fulfill the Scripture), \"I thirst\" (John 19:28)."),
("What does \"It is finished\" mean?", "Completed atonement — tetelestai", "Failed mission", "Only physical death", "Only rest", "It is finished (John 19:30)."),
("What does blood and water symbolize?", "Debated — sacraments, life given, medical witness to real death", "Only myth", "No meaning", "Contradicts resurrection", "Blood and water (John 19:34)."),
("How does Nicodemus reappear?", "Public burial courage — growth from chapter 3", "Still only night", "Never helps", "Denies Jesus", "Nicodemus… brought spices (John 19:39)."),
("What does new tomb show?", "No bones mixed — royal burial dignity", "Random hole", "Criminal dump only", "No prophecy", "In the garden a new tomb (John 19:41)."),
("Scholarly view: pierced side historicity?", "Medical arguments for fluid — apologetic for death", "No death", "Only spiritual", "No debate", "Blood and water discussed medically."),
("How does Passover timing emphasize?", "Lamb of God dies at preparation — typology", "Random day", "Contradicts Synoptics always", "No lamb imagery", "It was the day of Preparation (John 19:14)."),
("What does hyssop evoke?", "Passover lamb blood — Exodus imagery", "Random plant", "Only cleaning", "Greek myth", "They put it on hyssop (John 19:29)."),
("How does Joseph of Arimathea secret disciple now public?", "Courage after cross — costly discipleship", "Still fully secret", "Denies", "Only women brave", "Joseph… secretly for fear… asked Pilate (John 19:38)."),
("What does bones not broken fulfill?", "Exodus 12 / Psalm 34 — Passover lamb bones", "Random", "No prophecy", "Broken bones good", "Not one of his bones will be broken (John 19:36)."),
("How does Scripture fulfillment density function?", "Passion as word of God enacted — hermeneutic", "Coincidence", "No OT", "Only Paul", "These things occurred so that the Scripture might be fulfilled (John 19:36)."),
("What does King of Jews title before Jews mean?", "Irony — rejected king crucified publicly", "Jews accept", "Title is wrong", "Only for Romans", "Jesus of Nazareth, the King of the Jews (John 19:19)."),
("How does Mary's presence fulfill sword prophecy?", "Simeon's prophecy — soul pierced", "No connection", "Mary absent", "Only Luke", "Your own soul a sword will pierce (Luke 2:35 / John 19:25)."),
("What does finished accomplish?", "Atonement complete — priestly language", "Incomplete", "Only beginning", "Only physical", "It is finished (John 19:30)."),
("How does blood and water support sacraments tradition?", "Baptism and Eucharist imagery — church fathers", "Denied by John", "Only modern", "Only Catholic", "Blood and water (John 19:34)."),
("What does garden tomb evoke?", "Eden — new creation in resurrection hope", "Random", "No Eden", "Only agriculture", "In the garden… new tomb (John 19:41)."),
("How does Pilate's fear show?", "Tries to release — cowardice yields to crowd", "Bold always", "Loves Jesus", "No fear", "From then on Pilate sought to release him (John 19:12)."),
("What does Behold your King sarcasm become?", "Truth — Christians read as messianic irony", "Only joke", "No truth", "Pilate believes", "Behold your King! (John 19:14)."),
("How does crucifixion as lifting up connect John 3 and 12?", "Serpent / Son of Man lifted — drawing all", "No connection", "Only physical", "Denies spiritual", "They crucified him (John 19:18)."),
("What does Veronica-like silence in John omit?", "John focuses on Mary and beloved disciple — theological choice", "Contradicts other Gospels", "Women absent", "Only soldiers", "Standing by the cross… his mother (John 19:25)."),
("How does spices honor burial?", "Royal tons — king treated even in death", "Cheap burial", "No honor", "Only criminals", "Seventy-five pounds (John 19:39)."),
("What does pierced side fulfill?", "Zechariah 12:10 — look on pierced one", "No prophecy", "Random violence", "Only medical", "They will look on me whom they have pierced (John 19:37)."),
("How does Scripture not a bone broken cohere?", "Passover lamb — Jesus as lamb", "Contradicts Exodus", "Bones must break", "Only Paul", "Not one of his bones will be broken (John 19:36)."),
("What title did Pilate's inscription use — King of the Jews?", "Written in Hebrew, Latin, and Greek", "Only Hebrew", "Only Greek", "Only Latin", "Written in Hebrew, in Latin, and in Greek (John 19:20)."),
("What did the soldiers do after crucifying Jesus?", "Divided his garments and cast lots", "Left him clothed", "Burned garments", "Returned them to Mary", "When the soldiers had crucified Jesus, they took his garments and divided them into four parts (John 19:23)."),
]

_CH20: list[tuple[str, str, str, str, str, str]] = [
("On what day did Mary Magdalene come to the tomb?", "First day of the week", "Seventh day", "Third day only counted differently", "Passover day", "Now on the first day of the week Mary Magdalene came to the tomb early (John 20:1)."),
("What did she see about the stone?", "Taken away from the tomb", "Sealed tighter", "Angels sitting only", "Jesus waiting", "She saw that the stone had been taken away from the tomb (John 20:1)."),
("Whom did Mary run to tell?", "Simon Peter and the other disciple", "Only Romans", "Only Pharisees", "Her mother", "She ran and went to Simon Peter and the other disciple (John 20:2)."),
("What did the other disciple do at the tomb?", "Outran Peter but waited to enter", "Refused to go", "Stayed home", "Called soldiers", "The other disciple outran Peter (John 20:4)."),
("What did Peter see in the tomb?", "Linen cloths lying, face cloth folded separately", "Jesus body", "Angels eating", "Nothing", "He saw the linen cloths lying there, and the face cloth… folded (John 20:6–7)."),
("Who sat down in the tomb in angels' appearance?", "Two angels in white", "Four creatures", "Moses and Elijah", "Soldiers", "She saw two angels in white sitting (John 20:12)."),
("Whom did Mary think Jesus was?", "The gardener", "A soldier", "Peter", "A ghost", "Supposing him to be the gardener (John 20:15)."),
("What did Jesus say to Mary?", "Mary!", "Why weep?", "Touch me not yet", "Go to disciples", "Jesus said to her, \"Mary.\" She turned and said to him in Aramaic, \"Rabboni!\" (John 20:16)."),
("What did Jesus say — do not cling to him?", "I have not yet ascended to the Father", "I am a ghost", "I hate you", "Go away", "Do not cling to me, for I have not yet ascended to the Father (John 17)."),
("What did Jesus tell Mary to say?", "I am ascending to my Father and your Father", "I will never ascend", "Stay silent", "Flee to Egypt", "Go to my brothers and say to them, \"I am ascending…\" (John 20:17)."),
("When were disciples gathered on first day of week?", "Doors locked for fear of Jews", "Open festival", "Temple courts", "By the sea", "On the evening of that day… the doors being locked where the disciples were (John 20:19)."),
("What did Jesus show them?", "His hands and side", "Only face", "Only feet", "Coins", "He showed them his hands and his side (John 20:20)."),
("What did Jesus say?", "Peace be with you", "Why doubt?", "Touch me", "Go fishing", "Jesus said to them, \"Peace be with you\" (John 20:19)."),
("What did Jesus breathe on them and say?", "Receive the Holy Spirit", "Receive money", "Receive swords", "Receive fear", "He breathed on them and said to them, \"Receive the Holy Spirit\" (John 20:22)."),
("What power did Jesus give about forgiveness?", "If you forgive anyone's sins, they are forgiven", "No forgiveness", "Only angels forgive", "Only priests in Rome", "If you forgive the sins of any, they are forgiven them (John 20:23)."),
("Who was not there when Jesus came?", "Thomas", "Peter", "Mary", "Judas", "Now Thomas… was not with them when Jesus came (John 20:24)."),
("What did Thomas say he needed to see?", "The mark of nails in hands and put finger in side", "Angels", "The temple", "Pilate", "Unless I see in his hands the mark of the nails… I will never believe (John 20:25)."),
("What did Jesus tell Thomas to do?", "Put finger here, and see my hands; put out hand, place in side", "Go away", "Believe blindly", "Never touch", "Put your finger here, and see my hands; and put out your hand, and place it in my side (John 20:27)."),
("What did Thomas answer?", "My Lord and my God!", "A ghost!", "Who are you?", "Prove it", "Thomas answered him, \"My Lord and my God!\" (John 20:28)."),
("What did Jesus say about those who have not seen and believe?", "Blessed", "Cursed", "Neutral", "Ignorant", "Blessed are those who have not seen and yet have believed (John 20:29)."),
("Why did John say these were written?", "That you may believe Jesus is the Christ, the Son of God, and have life in his name", "Only history", "Only politics", "For entertainment", "These are written so that you may believe that Jesus is the Christ, the Son of God (John 20:31)."),
("Theologically, what does empty tomb prove?", "Resurrection body — not merely spiritualized", "Disciples stole always", "No body matters", "Only myth", "The linen cloths lying there (John 20:6–7)."),
("How does race between Peter and beloved disciple show?", "Humor and eyewitness detail — Peter still enters first", "Contradiction", "Only Peter ran", "No beloved disciple", "The other disciple… outran Peter (John 20:4)."),
("What does folded face cloth suggest?", "Orderly resurrection — not grave robbery chaos", "Thieves care", "Random", "No meaning", "The face cloth… folded in a place by itself (John 20:7)."),
("How does Mary mistaking Jesus show?", "Grief and hope — recognition at name", "Mary blind", "Jesus disguised badly", "No theology", "She turned and said… Rabboni (John 20:16)."),
("What does not clinging yet mean?", "Ascension theology — relationship changes but real", "No resurrection", "Gnosticism", "Mary sin", "Do not cling to me (John 20:17)."),
("How does peace and Spirit relate to new creation?", "Easter evening as new creation — breath like Genesis", "No Genesis echo", "Spirit only later", "Only Pentecost", "He breathed on them… Receive the Holy Spirit (John 20:22)."),
("What does forgiveness authority mean for church?", "Office of keys — debated among traditions", "Unlimited human power", "No forgiveness", "Only God forgives ever", "If you forgive… (John 20:23)."),
("How does Thomas' doubt help readers?", "Honest faith — Jesus meets doubt with wounds", "Thomas is villain", "Doubt is blessed", "Only Thomas doubts", "Put your finger here (John 20:27)."),
("What christological height in Thomas' confession?", "My God — highest title", "Only teacher", "Only man", "Only angel", "My Lord and my God! (John 20:28)."),
("Scholarly debate: 20:23 and church structure?", "Debates on apostolic unique vs. congregational forgiveness", "All agree", "No forgiveness text", "Only Catholic", "If you forgive… (John 20:23)."),
("How does blessed are those not seeing encourage?", "Later generations — faith without sight", "Curses moderns", "Only apostles blessed", "Sight required", "Blessed are those who have not seen and yet have believed (John 20:29)."),
("What does John's purpose statement mean for canon?", "Gospel sufficiency for salvation knowledge", "Bible incomplete", "Only tradition saves", "Only signs save", "That you may believe… and that by believing you may have life (John 20:31)."),
("How does locked doors show risen body?", "Jesus appears — glorified body properties", "Ghost only", "Doors stayed locked forever", "No body", "The doors being locked… Jesus came and stood among them (John 20:19)."),
("What does peace be with you repeat?", "Priestly blessing — new covenant peace", "Only once", "No peace", "Military peace", "Peace be with you (John 20:19, 21)."),
("How does Mary as apostle to apostles function?", "First witness — women in resurrection mission", "Women silent", "Only men preach", "Mary lied", "Mary Magdalene went and announced… (John 20:18)."),
("What does ascending to Father mean for theology?", "Session — exaltation continues Christology", "No ascension", "Only descent", "Only spirit", "I am ascending to my Father (John 20:17)."),
("How does Spirit given before Pentecost relate to Luke-Acts?", "Harmonization debates — symbolic, anticipatory, or sacramental", "Contradicts Acts", "No Spirit in John", "Only Pentecost", "Receive the Holy Spirit (John 20:22)."),
("What does joy of disciples show?", "Resurrection faith — fear to joy", "No emotion", "Only sadness", "Doubt forever", "Then the disciples were glad when they saw the Lord (John 20:20)."),
("How does second appearance for Thomas show patience?", "Jesus accommodates doubt — pastoral model", "Thomas excommunicated", "Doubt condemned always", "Only one chance", "Eight days later… (John 20:26)."),
("What does nail prints apologetic defend?", "Physical resurrection — not mere vision", "Vision only", "Docetism true", "No wounds", "See my hands (John 20:27)."),
("How does life in his name summarize Gospel?", "Eternal life gift through faith in Christ — thesis", "Only ethics", "Only miracles", "Only Israel", "Life in his name (John 20:31)."),
("What does weeping outside tomb show?", "Love and grief — human emotion of Jesus' friends", "Sin", "Weak faith", "Only Mary weeps", "She turned around and saw Jesus standing (John 20:14)."),
("How does garden setting recall crucifixion?", "Same geography — new creation continuity", "Random", "Different country", "No link", "At the tomb… in the garden (John 20:15)."),
("What does light darkness of first day evoke?", "Creation week — Christ firstfruits of new creation", "Evening only", "Sabbath only", "No creation", "First day of the week (John 20:1)."),
("How does Peter + beloved at tomb show unity?", "Apostolic and witness community — together", "Rivalry only", "Only one believer", "Contradiction", "Simon Peter… the other disciple (John 20:2–3)."),
("What does Jesus send Mary as mean?", "Mission — go tell brothers", "Mary forbidden", "Only men sent", "Silent mission", "Go to my brothers (John 20:17)."),
("How does 20:31 faith-life order work?", "Believing leads to life — not works first", "Works first", "Life without faith", "Only baptism", "By believing you may have life (John 20:31)."),
("How many other signs did Jesus do in the presence of the disciples that are not written in this book?", "Many — not all recorded", "None", "Exactly seven", "Exactly twelve", "Now Jesus did many other signs in the presence of the disciples… not written in this book (John 20:30)."),
("What did Jesus say to the disciples when he appeared in the locked room?", "Peace be with you — as the Father sent me, even so I am sending you", "Hide forever", "Do not preach", "Stay in the room", "Peace be with you. As the Father has sent me, even so I am sending you (John 20:21)."),
]

_CH21: list[tuple[str, str, str, str, str, str]] = [
("Where did Jesus reveal himself again?", "Sea of Tiberias", "Jordan", "Dead Sea", "Mediterranean", "After this Jesus revealed himself again to the disciples at the Sea of Tiberias (John 21:1)."),
("Who went fishing?", "Simon Peter, Thomas, Nathanael, sons of Zebedee, two others", "Only Peter", "Only women", "Romans", "Simon Peter… I am going fishing… (John 21:2–3)."),
("What did they catch?", "Nothing that night", "A full net at night", "One fish", "Whales", "That night they caught nothing (John 21:3)."),
("Who stood on the beach in the morning?", "Jesus", "A soldier", "Moses", "An angel", "Just as day was breaking, Jesus stood on the shore (John 21:4)."),
("What did Jesus tell them to cast?", "Net on the right side of the boat", "Net on left", "Hooks only", "Spears", "Cast the net on the right side of the boat, and you will find some (John 21:6)."),
("How many fish were caught?", "153 large fish", "Seven", "Twelve", "Two", "So many fish… 153 large ones (John 21:11)."),
("What did Jesus have on the fire?", "Fish and bread", "Lamb only", "Nothing", "Pork", "Jesus came and took the bread and gave it to them, and so with the fish (John 21:9–13)."),
("How many times did Jesus ask Peter if he loved him?", "Three", "Once", "Seven", "Twelve", "He said to him the third time, \"Simon… do you love me?\" (John 21:17)."),
("What did Jesus tell Peter to feed?", "My lambs / my sheep", "His money", "Romans", "Fish only", "Feed my lambs… Tend my sheep… Feed my sheep (John 21:15–17)."),
("What did Jesus say would happen when Peter was young?", "He dressed himself and went where he wished", "He was carried always", "He was poor", "He was silent", "When you were young, you used to dress yourself and walk wherever you wished (John 21:18)."),
("What did Jesus say about when Peter is old?", "Another will dress him and carry him where he does not wish", "He will be king", "He will be rich", "He will never die", "When you are old, you will stretch out your hands, and another will dress you (John 21:18)."),
("What did that signify?", "By what kind of death Peter would glorify God", "Peter's natural death only", "Judas' fate", "Paul's mission", "This he said to show by what kind of death he was to glorify God (John 21:19)."),
("What did Jesus say to Peter about following?", "Follow me", "Stay fishing", "Go to Rome", "Deny me", "Jesus said to him, \"Follow me\" (John 21:19)."),
("What did Peter ask about the beloved disciple?", "What about this man?", "Who is he?", "Is he rich?", "Will he betray?", "Peter… said to Jesus, \"Lord, what about this man?\" (John 21:21)."),
("What did Jesus answer?", "If it is my will that he remain until I come, what is that to you?", "He will die soon", "He is greater than you", "He will betray", "If it is my will that he remain until I come, what is that to you? You follow me! (John 21:22)."),
("What rumor spread about the beloved disciple?", "That he would not die", "That he was Judas", "That he was Paul", "That he was Peter", "So the saying spread among the brothers that this disciple would not die (John 21:23)."),
("Who does the Gospel say wrote these things?", "This disciple who testifies", "Matthew", "Moses", "Paul", "This is the disciple who is bearing witness about these things, and who has written these things (John 21:24)."),
("Theologically, what does 153 fish mean?", "Debated — symbolic fullness, or mundane detail — scholars differ", "Always one meaning", "No fish", "Only allegory everyone agrees", "Scholars debate significance of 153 (John 21:11)."),
("How does charcoal fire echo chapter 18?", "Restoration after denial — second chance", "No echo", "Different fire", "Only cold", "Charcoal fire… (John 21:9)."),
("What does threefold love question heal?", "Threefold denial — reconciliation", "Random repetition", "Peter rejected", "Only rhetorical", "Do you love me?… three times (John 21:15–17)."),
("How does feed my sheep commission Peter?", "Pastoral office — shepherd after failure", "Peter excluded", "Only Judas feeds", "Only angels", "Feed my sheep (John 21:17)."),
("What does follow me after prophecy mean?", "Discipleship continues despite martyrdom knowledge", "Peter refuses", "Only death", "No following", "Follow me (John 21:19)."),
("How does beloved disciple rumor correct?", "John clarifies Jesus did not say he wouldn't die", "John confirms immortality", "Disciple is angel", "Contradiction", "Jesus did not say to him that he would not die (John 21:23)."),
("What does Gospel truth claim in 21:24?", "Eyewitness verification — we know testimony true", "Anonymous only", "No witness", "Only angels", "We know that his testimony is true (John 21:24)."),
("Scholarly debate: chapter 21 appendix?", "Debates on unity of Gospel — majority see cohesive epilogue", "All reject ch.21", "John never wrote", "No debate", "Scholarship discusses appendix function."),
("How does fishing miracle echo chapter 6?", "Provision theme — risen Lord provides", "Contradicts ch.6", "No link", "Only numbers", "Full nets again (John 21:6)."),
("What does right side of boat symbolize?", "Debated — favor, or just narrative detail", "Left is blessed", "No meaning", "All agree", "Right side… (John 21:6)."),
("How does Peter jump into water show?", "Eagerness to be with Jesus — impulsive love", "Fear", "Cannot swim", "Hates Jesus", "Peter… threw himself into the sea (John 21:7)."),
("What does breakfast on beach mean?", "Communion fellowship — Lord serves disciples", "Only food", "Law meal", "Passover repeat", "Come and have breakfast (John 21:12)."),
("How does shepherd language continue ch.10?", "Jesus commissions Peter as under-shepherd", "Breaks ch.10", "Only Jesus shepherd", "Peter replaces Jesus", "Tend my sheep (John 21:16)."),
("What does stretch hands prophecy mean?", "Peter crucifixion tradition — early church memory", "Natural death only", "Peter escapes", "Only metaphor", "By what kind of death… (John 21:19)."),
("How does what about this man teach?", "Comparing callings is wrong — each follows Jesus", "Competition good", "Beloved disciple greater always", "Peter inferior forever", "What is that to you? You follow me! (John 21:22)."),
("What evangelistic note in epilogue?", "Restored Peter — failure is not final", "Peter damned", "No restoration", "Only Paul matters", "Feed my sheep (John 21:17)."),
("How does net not breaking echo?", "Abundance without loss — church imagery possible", "Contradicts Luke 5", "Net always breaks", "No meaning", "The net was not torn (John 21:11)."),
("What does Lord know all things (21:17) show?", "Jesus' omniscience — Peter's affirmation", "Jesus guesses", "Peter hides", "No deity", "Lord, you know everything (John 21:17)."),
("How does third \"Do you love me\" with greek words vary?", "Agapao vs phileo debate — pastoral nuance or translation", "No variation", "Copyist error only", "Only English issue", "Scholars debate verb nuances (John 21:15–17)."),
("What does 21:25 hyperbole mean?", "World cannot contain books — gospel selective not exhaustive", "John failed", "Everything written", "Only myths left", "The world itself could not contain the books (John 21:25)."),
("How does epilogue close mission?", "From fishing to shepherding — from business to pastoral care", "Mission ends", "Only fishing", "Only Paul continues", "Feed my sheep (John 21:17)."),
("What does Jesus reveal himself third time mean?", "Echoes earlier appearances — completeness", "Contradicts seven", "Only two appearances", "No resurrection", "This was now the third time that Jesus was revealed to the disciples (John 21:14)."),
("How does seaside setting recall call of fishermen?", "Mark 1 / Luke 5 echo — new beginning after resurrection", "No OT", "Only Paul", "Random job", "I am going fishing (John 21:3)."),
("What pastoral use in Peter's restoration?", "Leaders who fail can be reinstated — grace", "No second chances", "Only Peter", "Denial is unforgivable", "Simon… do you love me? (John 21:15–17)."),
("How does beloved disciple identity function?", "Witness authority for Gospel — apostolic eyewitness", "Anonymous forever", "Judas wrote", "Paul wrote", "The disciple whom Jesus loved… (John 21:7, 20)."),
("What christological note in miraculous catch?", "Risen Lord is same who multiplied bread — continuity", "Different Jesus", "Spirit only", "No body", "It is the Lord! (John 21:7)."),
("How does Gospel end open-ended?", "You follow me — ongoing discipleship", "Story complete closed", "No application", "Ends in fear", "You follow me! (John 21:22)."),
("What does true testimony ending affirm?", "Scripture reliability — Spirit-guided witness", "Gospels false", "Only oral", "No truth", "We know that his testimony is true (John 21:24)."),
("How does Peter's death glorify God?", "Martyrdom as witness — Father honored", "God needs death", "Glorify means only praise words", "Only resurrection", "Glorify God (John 21:19)."),
("What does remain until I come mean?", "Eschatological reserve — some matters unknown", "Immortality promise", "Date setting", "Nothing remains", "Until I come (John 21:22)."),
("What did Jesus say to the disciples when they were fishing?", "Children, do you have any fish?", "Why are you lazy?", "Go home", "Leave me", "Jesus said to them, \"Children, do you have any fish?\" They answered him, \"No\" (John 21:5)."),
("What did the beloved disciple say when Peter said it is the Lord?", "It is the Lord!", "It is a ghost", "It is a soldier", "It is Moses", "That disciple whom Jesus loved… said, \"It is the Lord!\" (John 21:7)."),
("When Jesus served breakfast, what did he take and give?", "Bread and fish", "Only meat", "Only wine", "Only bread", "Jesus took the bread and gave it to them, and so with the fish (John 21:13)."),
]


def all_chapters() -> list[dict]:
    return (
        zip_chapter(15, _CH15)
        + zip_chapter(16, _CH16)
        + zip_chapter(17, _CH17)
        + zip_chapter(18, _CH18)
        + zip_chapter(19, _CH19)
        + zip_chapter(20, _CH20)
        + zip_chapter(21, _CH21)
    )
