from __future__ import annotations


BOOK_DATA = [
    {"number": 1, "osis": "GEN", "name": "Genesis", "name_zh": "創世紀", "testament": "OT", "chapters": 50},
    {"number": 2, "osis": "EXO", "name": "Exodus", "name_zh": "出埃及記", "testament": "OT", "chapters": 40},
    {"number": 3, "osis": "LEV", "name": "Leviticus", "name_zh": "利未記", "testament": "OT", "chapters": 27},
    {"number": 4, "osis": "NUM", "name": "Numbers", "name_zh": "民數記", "testament": "OT", "chapters": 36},
    {"number": 5, "osis": "DEU", "name": "Deuteronomy", "name_zh": "申命記", "testament": "OT", "chapters": 34},
    {"number": 6, "osis": "JOS", "name": "Joshua", "name_zh": "約書亞記", "testament": "OT", "chapters": 24},
    {"number": 7, "osis": "JDG", "name": "Judges", "name_zh": "士師記", "testament": "OT", "chapters": 21},
    {"number": 8, "osis": "RUT", "name": "Ruth", "name_zh": "路得記", "testament": "OT", "chapters": 4},
    {"number": 9, "osis": "1SA", "name": "1 Samuel", "name_zh": "撒母耳記上", "testament": "OT", "chapters": 31},
    {"number": 10, "osis": "2SA", "name": "2 Samuel", "name_zh": "撒母耳記下", "testament": "OT", "chapters": 24},
    {"number": 11, "osis": "1KI", "name": "1 Kings", "name_zh": "列王紀上", "testament": "OT", "chapters": 22},
    {"number": 12, "osis": "2KI", "name": "2 Kings", "name_zh": "列王紀下", "testament": "OT", "chapters": 25},
    {"number": 13, "osis": "1CH", "name": "1 Chronicles", "name_zh": "歷代志上", "testament": "OT", "chapters": 29},
    {"number": 14, "osis": "2CH", "name": "2 Chronicles", "name_zh": "歷代志下", "testament": "OT", "chapters": 36},
    {"number": 15, "osis": "EZR", "name": "Ezra", "name_zh": "以斯拉記", "testament": "OT", "chapters": 10},
    {"number": 16, "osis": "NEH", "name": "Nehemiah", "name_zh": "尼希米記", "testament": "OT", "chapters": 13},
    {"number": 17, "osis": "EST", "name": "Esther", "name_zh": "以斯帖記", "testament": "OT", "chapters": 10},
    {"number": 18, "osis": "JOB", "name": "Job", "name_zh": "約伯記", "testament": "OT", "chapters": 42},
    {"number": 19, "osis": "PSA", "name": "Psalms", "name_zh": "詩篇", "testament": "OT", "chapters": 150},
    {"number": 20, "osis": "PRO", "name": "Proverbs", "name_zh": "箴言", "testament": "OT", "chapters": 31},
    {"number": 21, "osis": "ECC", "name": "Ecclesiastes", "name_zh": "傳道書", "testament": "OT", "chapters": 12},
    {"number": 22, "osis": "SNG", "name": "Song of Solomon", "name_zh": "雅歌", "testament": "OT", "chapters": 8},
    {"number": 23, "osis": "ISA", "name": "Isaiah", "name_zh": "以賽亞書", "testament": "OT", "chapters": 66},
    {"number": 24, "osis": "JER", "name": "Jeremiah", "name_zh": "耶利米書", "testament": "OT", "chapters": 52},
    {"number": 25, "osis": "LAM", "name": "Lamentations", "name_zh": "耶利米哀歌", "testament": "OT", "chapters": 5},
    {"number": 26, "osis": "EZK", "name": "Ezekiel", "name_zh": "以西結書", "testament": "OT", "chapters": 48},
    {"number": 27, "osis": "DAN", "name": "Daniel", "name_zh": "但以理書", "testament": "OT", "chapters": 12},
    {"number": 28, "osis": "HOS", "name": "Hosea", "name_zh": "何西阿書", "testament": "OT", "chapters": 14},
    {"number": 29, "osis": "JOL", "name": "Joel", "name_zh": "約珥書", "testament": "OT", "chapters": 3},
    {"number": 30, "osis": "AMO", "name": "Amos", "name_zh": "阿摩司書", "testament": "OT", "chapters": 9},
    {"number": 31, "osis": "OBA", "name": "Obadiah", "name_zh": "俄巴底亞書", "testament": "OT", "chapters": 1},
    {"number": 32, "osis": "JON", "name": "Jonah", "name_zh": "約拿書", "testament": "OT", "chapters": 4},
    {"number": 33, "osis": "MIC", "name": "Micah", "name_zh": "彌迦書", "testament": "OT", "chapters": 7},
    {"number": 34, "osis": "NAM", "name": "Nahum", "name_zh": "那鴻書", "testament": "OT", "chapters": 3},
    {"number": 35, "osis": "HAB", "name": "Habakkuk", "name_zh": "哈巴谷書", "testament": "OT", "chapters": 3},
    {"number": 36, "osis": "ZEP", "name": "Zephaniah", "name_zh": "西番雅書", "testament": "OT", "chapters": 3},
    {"number": 37, "osis": "HAG", "name": "Haggai", "name_zh": "哈該書", "testament": "OT", "chapters": 2},
    {"number": 38, "osis": "ZEC", "name": "Zechariah", "name_zh": "撒迦利亞書", "testament": "OT", "chapters": 14},
    {"number": 39, "osis": "MAL", "name": "Malachi", "name_zh": "瑪拉基書", "testament": "OT", "chapters": 4},
    {"number": 40, "osis": "MAT", "name": "Matthew", "name_zh": "馬太福音", "testament": "NT", "chapters": 28},
    {"number": 41, "osis": "MRK", "name": "Mark", "name_zh": "馬可福音", "testament": "NT", "chapters": 16},
    {"number": 42, "osis": "LUK", "name": "Luke", "name_zh": "路加福音", "testament": "NT", "chapters": 24},
    {"number": 43, "osis": "JHN", "name": "John", "name_zh": "約翰福音", "testament": "NT", "chapters": 21},
    {"number": 44, "osis": "ACT", "name": "Acts", "name_zh": "使徒行傳", "testament": "NT", "chapters": 28},
    {"number": 45, "osis": "ROM", "name": "Romans", "name_zh": "羅馬書", "testament": "NT", "chapters": 16},
    {"number": 46, "osis": "1CO", "name": "1 Corinthians", "name_zh": "哥林多前書", "testament": "NT", "chapters": 16},
    {"number": 47, "osis": "2CO", "name": "2 Corinthians", "name_zh": "哥林多後書", "testament": "NT", "chapters": 13},
    {"number": 48, "osis": "GAL", "name": "Galatians", "name_zh": "加拉太書", "testament": "NT", "chapters": 6},
    {"number": 49, "osis": "EPH", "name": "Ephesians", "name_zh": "以弗所書", "testament": "NT", "chapters": 6},
    {"number": 50, "osis": "PHP", "name": "Philippians", "name_zh": "腓利比書", "testament": "NT", "chapters": 4},
    {"number": 51, "osis": "COL", "name": "Colossians", "name_zh": "歌羅西書", "testament": "NT", "chapters": 4},
    {"number": 52, "osis": "1TH", "name": "1 Thessalonians", "name_zh": "帖撒羅尼迦前書", "testament": "NT", "chapters": 5},
    {"number": 53, "osis": "2TH", "name": "2 Thessalonians", "name_zh": "帖撒羅尼迦後書", "testament": "NT", "chapters": 3},
    {"number": 54, "osis": "1TI", "name": "1 Timothy", "name_zh": "提摩太前書", "testament": "NT", "chapters": 6},
    {"number": 55, "osis": "2TI", "name": "2 Timothy", "name_zh": "提摩太後書", "testament": "NT", "chapters": 4},
    {"number": 56, "osis": "TIT", "name": "Titus", "name_zh": "提多書", "testament": "NT", "chapters": 3},
    {"number": 57, "osis": "PHM", "name": "Philemon", "name_zh": "腓利門書", "testament": "NT", "chapters": 1},
    {"number": 58, "osis": "HEB", "name": "Hebrews", "name_zh": "希伯來書", "testament": "NT", "chapters": 13},
    {"number": 59, "osis": "JAS", "name": "James", "name_zh": "雅各書", "testament": "NT", "chapters": 5},
    {"number": 60, "osis": "1PE", "name": "1 Peter", "name_zh": "彼得前書", "testament": "NT", "chapters": 5},
    {"number": 61, "osis": "2PE", "name": "2 Peter", "name_zh": "彼得後書", "testament": "NT", "chapters": 3},
    {"number": 62, "osis": "1JN", "name": "1 John", "name_zh": "約翰壹書", "testament": "NT", "chapters": 5},
    {"number": 63, "osis": "2JN", "name": "2 John", "name_zh": "約翰貳書", "testament": "NT", "chapters": 1},
    {"number": 64, "osis": "3JN", "name": "3 John", "name_zh": "約翰參書", "testament": "NT", "chapters": 1},
    {"number": 65, "osis": "JUD", "name": "Jude", "name_zh": "猶大書", "testament": "NT", "chapters": 1},
    {"number": 66, "osis": "REV", "name": "Revelation", "name_zh": "啟示錄", "testament": "NT", "chapters": 22},
]

BOOK_NAMES_ZH_SIMP = {
    1: "创世纪",
    2: "出埃及记",
    3: "利未记",
    4: "民数记",
    5: "申命记",
    6: "约书亚记",
    7: "士师记",
    8: "路得记",
    9: "撒母耳记上",
    10: "撒母耳记下",
    11: "列王纪上",
    12: "列王纪下",
    13: "历代志上",
    14: "历代志下",
    15: "以斯拉记",
    16: "尼希米记",
    17: "以斯帖记",
    18: "约伯记",
    19: "诗篇",
    20: "箴言",
    21: "传道书",
    22: "雅歌",
    23: "以赛亚书",
    24: "耶利米书",
    25: "耶利米哀歌",
    26: "以西结书",
    27: "但以理书",
    28: "何西阿书",
    29: "约珥书",
    30: "阿摩司书",
    31: "俄巴底亚书",
    32: "约拿书",
    33: "弥迦书",
    34: "那鸿书",
    35: "哈巴谷书",
    36: "西番雅书",
    37: "哈该书",
    38: "撒迦利亚书",
    39: "玛拉基书",
    40: "马太福音",
    41: "马可福音",
    42: "路加福音",
    43: "约翰福音",
    44: "使徒行传",
    45: "罗马书",
    46: "哥林多前书",
    47: "哥林多后书",
    48: "加拉太书",
    49: "以弗所书",
    50: "腓利比书",
    51: "歌罗西书",
    52: "帖撒罗尼迦前书",
    53: "帖撒罗尼迦后书",
    54: "提摩太前书",
    55: "提摩太后书",
    56: "提多书",
    57: "腓利门书",
    58: "希伯来书",
    59: "雅各书",
    60: "彼得前书",
    61: "彼得后书",
    62: "约翰壹书",
    63: "约翰贰书",
    64: "约翰参书",
    65: "犹大书",
    66: "启示录",
}

for book in BOOK_DATA:
    book["name_zh_simplified"] = BOOK_NAMES_ZH_SIMP[book["number"]]

BOOK_BY_NUMBER = {book["number"]: book for book in BOOK_DATA}
BOOK_BY_OSIS = {book["osis"]: book for book in BOOK_DATA}
